// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	etcd "go.etcd.io/etcd/client/v3"
)

// EtcdClientMock implements mm_etcd.Client
type EtcdClientMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcTxn          func(ctx context.Context) (t1 etcd.Txn)
	funcTxnOrigin    string
	inspectFuncTxn   func(ctx context.Context)
	afterTxnCounter  uint64
	beforeTxnCounter uint64
	TxnMock          mEtcdClientMockTxn
}

// NewEtcdClientMock returns a mock for mm_etcd.Client
func NewEtcdClientMock(t minimock.Tester) *EtcdClientMock {
	m := &EtcdClientMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.TxnMock = mEtcdClientMockTxn{mock: m}
	m.TxnMock.callArgs = []*EtcdClientMockTxnParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mEtcdClientMockTxn struct {
	optional           bool
	mock               *EtcdClientMock
	defaultExpectation *EtcdClientMockTxnExpectation
	expectations       []*EtcdClientMockTxnExpectation

	callArgs []*EtcdClientMockTxnParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// EtcdClientMockTxnExpectation specifies expectation struct of the Client.Txn
type EtcdClientMockTxnExpectation struct {
	mock               *EtcdClientMock
	params             *EtcdClientMockTxnParams
	paramPtrs          *EtcdClientMockTxnParamPtrs
	expectationOrigins EtcdClientMockTxnExpectationOrigins
	results            *EtcdClientMockTxnResults
	returnOrigin       string
	Counter            uint64
}

// EtcdClientMockTxnParams contains parameters of the Client.Txn
type EtcdClientMockTxnParams struct {
	ctx context.Context
}

// EtcdClientMockTxnParamPtrs contains pointers to parameters of the Client.Txn
type EtcdClientMockTxnParamPtrs struct {
	ctx *context.Context
}

// EtcdClientMockTxnResults contains results of the Client.Txn
type EtcdClientMockTxnResults struct {
	t1 etcd.Txn
}

// EtcdClientMockTxnOrigins contains origins of expectations of the Client.Txn
type EtcdClientMockTxnExpectationOrigins struct {
	origin    string
	originCtx string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmTxn *mEtcdClientMockTxn) Optional() *mEtcdClientMockTxn {
	mmTxn.optional = true
	return mmTxn
}

// Expect sets up expected params for Client.Txn
func (mmTxn *mEtcdClientMockTxn) Expect(ctx context.Context) *mEtcdClientMockTxn {
	if mmTxn.mock.funcTxn != nil {
		mmTxn.mock.t.Fatalf("EtcdClientMock.Txn mock is already set by Set")
	}

	if mmTxn.defaultExpectation == nil {
		mmTxn.defaultExpectation = &EtcdClientMockTxnExpectation{}
	}

	if mmTxn.defaultExpectation.paramPtrs != nil {
		mmTxn.mock.t.Fatalf("EtcdClientMock.Txn mock is already set by ExpectParams functions")
	}

	mmTxn.defaultExpectation.params = &EtcdClientMockTxnParams{ctx}
	mmTxn.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmTxn.expectations {
		if minimock.Equal(e.params, mmTxn.defaultExpectation.params) {
			mmTxn.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmTxn.defaultExpectation.params)
		}
	}

	return mmTxn
}

// ExpectCtxParam1 sets up expected param ctx for Client.Txn
func (mmTxn *mEtcdClientMockTxn) ExpectCtxParam1(ctx context.Context) *mEtcdClientMockTxn {
	if mmTxn.mock.funcTxn != nil {
		mmTxn.mock.t.Fatalf("EtcdClientMock.Txn mock is already set by Set")
	}

	if mmTxn.defaultExpectation == nil {
		mmTxn.defaultExpectation = &EtcdClientMockTxnExpectation{}
	}

	if mmTxn.defaultExpectation.params != nil {
		mmTxn.mock.t.Fatalf("EtcdClientMock.Txn mock is already set by Expect")
	}

	if mmTxn.defaultExpectation.paramPtrs == nil {
		mmTxn.defaultExpectation.paramPtrs = &EtcdClientMockTxnParamPtrs{}
	}
	mmTxn.defaultExpectation.paramPtrs.ctx = &ctx
	mmTxn.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmTxn
}

// Inspect accepts an inspector function that has same arguments as the Client.Txn
func (mmTxn *mEtcdClientMockTxn) Inspect(f func(ctx context.Context)) *mEtcdClientMockTxn {
	if mmTxn.mock.inspectFuncTxn != nil {
		mmTxn.mock.t.Fatalf("Inspect function is already set for EtcdClientMock.Txn")
	}

	mmTxn.mock.inspectFuncTxn = f

	return mmTxn
}

// Return sets up results that will be returned by Client.Txn
func (mmTxn *mEtcdClientMockTxn) Return(t1 etcd.Txn) *EtcdClientMock {
	if mmTxn.mock.funcTxn != nil {
		mmTxn.mock.t.Fatalf("EtcdClientMock.Txn mock is already set by Set")
	}

	if mmTxn.defaultExpectation == nil {
		mmTxn.defaultExpectation = &EtcdClientMockTxnExpectation{mock: mmTxn.mock}
	}
	mmTxn.defaultExpectation.results = &EtcdClientMockTxnResults{t1}
	mmTxn.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmTxn.mock
}

// Set uses given function f to mock the Client.Txn method
func (mmTxn *mEtcdClientMockTxn) Set(f func(ctx context.Context) (t1 etcd.Txn)) *EtcdClientMock {
	if mmTxn.defaultExpectation != nil {
		mmTxn.mock.t.Fatalf("Default expectation is already set for the Client.Txn method")
	}

	if len(mmTxn.expectations) > 0 {
		mmTxn.mock.t.Fatalf("Some expectations are already set for the Client.Txn method")
	}

	mmTxn.mock.funcTxn = f
	mmTxn.mock.funcTxnOrigin = minimock.CallerInfo(1)
	return mmTxn.mock
}

// When sets expectation for the Client.Txn which will trigger the result defined by the following
// Then helper
func (mmTxn *mEtcdClientMockTxn) When(ctx context.Context) *EtcdClientMockTxnExpectation {
	if mmTxn.mock.funcTxn != nil {
		mmTxn.mock.t.Fatalf("EtcdClientMock.Txn mock is already set by Set")
	}

	expectation := &EtcdClientMockTxnExpectation{
		mock:               mmTxn.mock,
		params:             &EtcdClientMockTxnParams{ctx},
		expectationOrigins: EtcdClientMockTxnExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmTxn.expectations = append(mmTxn.expectations, expectation)
	return expectation
}

// Then sets up Client.Txn return parameters for the expectation previously defined by the When method
func (e *EtcdClientMockTxnExpectation) Then(t1 etcd.Txn) *EtcdClientMock {
	e.results = &EtcdClientMockTxnResults{t1}
	return e.mock
}

// Times sets number of times Client.Txn should be invoked
func (mmTxn *mEtcdClientMockTxn) Times(n uint64) *mEtcdClientMockTxn {
	if n == 0 {
		mmTxn.mock.t.Fatalf("Times of EtcdClientMock.Txn mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmTxn.expectedInvocations, n)
	mmTxn.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmTxn
}

func (mmTxn *mEtcdClientMockTxn) invocationsDone() bool {
	if len(mmTxn.expectations) == 0 && mmTxn.defaultExpectation == nil && mmTxn.mock.funcTxn == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmTxn.mock.afterTxnCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmTxn.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Txn implements mm_etcd.Client
func (mmTxn *EtcdClientMock) Txn(ctx context.Context) (t1 etcd.Txn) {
	mm_atomic.AddUint64(&mmTxn.beforeTxnCounter, 1)
	defer mm_atomic.AddUint64(&mmTxn.afterTxnCounter, 1)

	mmTxn.t.Helper()

	if mmTxn.inspectFuncTxn != nil {
		mmTxn.inspectFuncTxn(ctx)
	}

	mm_params := EtcdClientMockTxnParams{ctx}

	// Record call args
	mmTxn.TxnMock.mutex.Lock()
	mmTxn.TxnMock.callArgs = append(mmTxn.TxnMock.callArgs, &mm_params)
	mmTxn.TxnMock.mutex.Unlock()

	for _, e := range mmTxn.TxnMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.t1
		}
	}

	if mmTxn.TxnMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmTxn.TxnMock.defaultExpectation.Counter, 1)
		mm_want := mmTxn.TxnMock.defaultExpectation.params
		mm_want_ptrs := mmTxn.TxnMock.defaultExpectation.paramPtrs

		mm_got := EtcdClientMockTxnParams{ctx}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmTxn.t.Errorf("EtcdClientMock.Txn got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmTxn.TxnMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmTxn.t.Errorf("EtcdClientMock.Txn got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmTxn.TxnMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmTxn.TxnMock.defaultExpectation.results
		if mm_results == nil {
			mmTxn.t.Fatal("No results are set for the EtcdClientMock.Txn")
		}
		return (*mm_results).t1
	}
	if mmTxn.funcTxn != nil {
		return mmTxn.funcTxn(ctx)
	}
	mmTxn.t.Fatalf("Unexpected call to EtcdClientMock.Txn. %v", ctx)
	return
}

// TxnAfterCounter returns a count of finished EtcdClientMock.Txn invocations
func (mmTxn *EtcdClientMock) TxnAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmTxn.afterTxnCounter)
}

// TxnBeforeCounter returns a count of EtcdClientMock.Txn invocations
func (mmTxn *EtcdClientMock) TxnBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmTxn.beforeTxnCounter)
}

// Calls returns a list of arguments used in each call to EtcdClientMock.Txn.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmTxn *mEtcdClientMockTxn) Calls() []*EtcdClientMockTxnParams {
	mmTxn.mutex.RLock()

	argCopy := make([]*EtcdClientMockTxnParams, len(mmTxn.callArgs))
	copy(argCopy, mmTxn.callArgs)

	mmTxn.mutex.RUnlock()

	return argCopy
}

// MinimockTxnDone returns true if the count of the Txn invocations corresponds
// the number of defined expectations
func (m *EtcdClientMock) MinimockTxnDone() bool {
	if m.TxnMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.TxnMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.TxnMock.invocationsDone()
}

// MinimockTxnInspect logs each unmet expectation
func (m *EtcdClientMock) MinimockTxnInspect() {
	for _, e := range m.TxnMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to EtcdClientMock.Txn at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterTxnCounter := mm_atomic.LoadUint64(&m.afterTxnCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.TxnMock.defaultExpectation != nil && afterTxnCounter < 1 {
		if m.TxnMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to EtcdClientMock.Txn at\n%s", m.TxnMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to EtcdClientMock.Txn at\n%s with params: %#v", m.TxnMock.defaultExpectation.expectationOrigins.origin, *m.TxnMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcTxn != nil && afterTxnCounter < 1 {
		m.t.Errorf("Expected call to EtcdClientMock.Txn at\n%s", m.funcTxnOrigin)
	}

	if !m.TxnMock.invocationsDone() && afterTxnCounter > 0 {
		m.t.Errorf("Expected %d calls to EtcdClientMock.Txn at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.TxnMock.expectedInvocations), m.TxnMock.expectedInvocationsOrigin, afterTxnCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *EtcdClientMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockTxnInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *EtcdClientMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *EtcdClientMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockTxnDone()
}
