// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// LockerMock implements mm_locker.Locker
type LockerMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcKey          func() (s1 string)
	funcKeyOrigin    string
	inspectFuncKey   func()
	afterKeyCounter  uint64
	beforeKeyCounter uint64
	KeyMock          mLockerMockKey

	funcLock          func(ctx context.Context) (err error)
	funcLockOrigin    string
	inspectFuncLock   func(ctx context.Context)
	afterLockCounter  uint64
	beforeLockCounter uint64
	LockMock          mLockerMockLock

	funcTryLock          func(ctx context.Context) (err error)
	funcTryLockOrigin    string
	inspectFuncTryLock   func(ctx context.Context)
	afterTryLockCounter  uint64
	beforeTryLockCounter uint64
	TryLockMock          mLockerMockTryLock

	funcUnlock          func(ctx context.Context) (err error)
	funcUnlockOrigin    string
	inspectFuncUnlock   func(ctx context.Context)
	afterUnlockCounter  uint64
	beforeUnlockCounter uint64
	UnlockMock          mLockerMockUnlock
}

// NewLockerMock returns a mock for mm_locker.Locker
func NewLockerMock(t minimock.Tester) *LockerMock {
	m := &LockerMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.KeyMock = mLockerMockKey{mock: m}

	m.LockMock = mLockerMockLock{mock: m}
	m.LockMock.callArgs = []*LockerMockLockParams{}

	m.TryLockMock = mLockerMockTryLock{mock: m}
	m.TryLockMock.callArgs = []*LockerMockTryLockParams{}

	m.UnlockMock = mLockerMockUnlock{mock: m}
	m.UnlockMock.callArgs = []*LockerMockUnlockParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mLockerMockKey struct {
	optional           bool
	mock               *LockerMock
	defaultExpectation *LockerMockKeyExpectation
	expectations       []*LockerMockKeyExpectation

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LockerMockKeyExpectation specifies expectation struct of the Locker.Key
type LockerMockKeyExpectation struct {
	mock *LockerMock

	results      *LockerMockKeyResults
	returnOrigin string
	Counter      uint64
}

// LockerMockKeyResults contains results of the Locker.Key
type LockerMockKeyResults struct {
	s1 string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmKey *mLockerMockKey) Optional() *mLockerMockKey {
	mmKey.optional = true
	return mmKey
}

// Expect sets up expected params for Locker.Key
func (mmKey *mLockerMockKey) Expect() *mLockerMockKey {
	if mmKey.mock.funcKey != nil {
		mmKey.mock.t.Fatalf("LockerMock.Key mock is already set by Set")
	}

	if mmKey.defaultExpectation == nil {
		mmKey.defaultExpectation = &LockerMockKeyExpectation{}
	}

	return mmKey
}

// Inspect accepts an inspector function that has same arguments as the Locker.Key
func (mmKey *mLockerMockKey) Inspect(f func()) *mLockerMockKey {
	if mmKey.mock.inspectFuncKey != nil {
		mmKey.mock.t.Fatalf("Inspect function is already set for LockerMock.Key")
	}

	mmKey.mock.inspectFuncKey = f

	return mmKey
}

// Return sets up results that will be returned by Locker.Key
func (mmKey *mLockerMockKey) Return(s1 string) *LockerMock {
	if mmKey.mock.funcKey != nil {
		mmKey.mock.t.Fatalf("LockerMock.Key mock is already set by Set")
	}

	if mmKey.defaultExpectation == nil {
		mmKey.defaultExpectation = &LockerMockKeyExpectation{mock: mmKey.mock}
	}
	mmKey.defaultExpectation.results = &LockerMockKeyResults{s1}
	mmKey.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmKey.mock
}

// Set uses given function f to mock the Locker.Key method
func (mmKey *mLockerMockKey) Set(f func() (s1 string)) *LockerMock {
	if mmKey.defaultExpectation != nil {
		mmKey.mock.t.Fatalf("Default expectation is already set for the Locker.Key method")
	}

	if len(mmKey.expectations) > 0 {
		mmKey.mock.t.Fatalf("Some expectations are already set for the Locker.Key method")
	}

	mmKey.mock.funcKey = f
	mmKey.mock.funcKeyOrigin = minimock.CallerInfo(1)
	return mmKey.mock
}

// Times sets number of times Locker.Key should be invoked
func (mmKey *mLockerMockKey) Times(n uint64) *mLockerMockKey {
	if n == 0 {
		mmKey.mock.t.Fatalf("Times of LockerMock.Key mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmKey.expectedInvocations, n)
	mmKey.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmKey
}

func (mmKey *mLockerMockKey) invocationsDone() bool {
	if len(mmKey.expectations) == 0 && mmKey.defaultExpectation == nil && mmKey.mock.funcKey == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmKey.mock.afterKeyCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmKey.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Key implements mm_locker.Locker
func (mmKey *LockerMock) Key() (s1 string) {
	mm_atomic.AddUint64(&mmKey.beforeKeyCounter, 1)
	defer mm_atomic.AddUint64(&mmKey.afterKeyCounter, 1)

	mmKey.t.Helper()

	if mmKey.inspectFuncKey != nil {
		mmKey.inspectFuncKey()
	}

	if mmKey.KeyMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmKey.KeyMock.defaultExpectation.Counter, 1)

		mm_results := mmKey.KeyMock.defaultExpectation.results
		if mm_results == nil {
			mmKey.t.Fatal("No results are set for the LockerMock.Key")
		}
		return (*mm_results).s1
	}
	if mmKey.funcKey != nil {
		return mmKey.funcKey()
	}
	mmKey.t.Fatalf("Unexpected call to LockerMock.Key.")
	return
}

// KeyAfterCounter returns a count of finished LockerMock.Key invocations
func (mmKey *LockerMock) KeyAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmKey.afterKeyCounter)
}

// KeyBeforeCounter returns a count of LockerMock.Key invocations
func (mmKey *LockerMock) KeyBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmKey.beforeKeyCounter)
}

// MinimockKeyDone returns true if the count of the Key invocations corresponds
// the number of defined expectations
func (m *LockerMock) MinimockKeyDone() bool {
	if m.KeyMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.KeyMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.KeyMock.invocationsDone()
}

// MinimockKeyInspect logs each unmet expectation
func (m *LockerMock) MinimockKeyInspect() {
	for _, e := range m.KeyMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to LockerMock.Key")
		}
	}

	afterKeyCounter := mm_atomic.LoadUint64(&m.afterKeyCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.KeyMock.defaultExpectation != nil && afterKeyCounter < 1 {
		m.t.Errorf("Expected call to LockerMock.Key at\n%s", m.KeyMock.defaultExpectation.returnOrigin)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcKey != nil && afterKeyCounter < 1 {
		m.t.Errorf("Expected call to LockerMock.Key at\n%s", m.funcKeyOrigin)
	}

	if !m.KeyMock.invocationsDone() && afterKeyCounter > 0 {
		m.t.Errorf("Expected %d calls to LockerMock.Key at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.KeyMock.expectedInvocations), m.KeyMock.expectedInvocationsOrigin, afterKeyCounter)
	}
}

type mLockerMockLock struct {
	optional           bool
	mock               *LockerMock
	defaultExpectation *LockerMockLockExpectation
	expectations       []*LockerMockLockExpectation

	callArgs []*LockerMockLockParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LockerMockLockExpectation specifies expectation struct of the Locker.Lock
type LockerMockLockExpectation struct {
	mock               *LockerMock
	params             *LockerMockLockParams
	paramPtrs          *LockerMockLockParamPtrs
	expectationOrigins LockerMockLockExpectationOrigins
	results            *LockerMockLockResults
	returnOrigin       string
	Counter            uint64
}

// LockerMockLockParams contains parameters of the Locker.Lock
type LockerMockLockParams struct {
	ctx context.Context
}

// LockerMockLockParamPtrs contains pointers to parameters of the Locker.Lock
type LockerMockLockParamPtrs struct {
	ctx *context.Context
}

// LockerMockLockResults contains results of the Locker.Lock
type LockerMockLockResults struct {
	err error
}

// LockerMockLockOrigins contains origins of expectations of the Locker.Lock
type LockerMockLockExpectationOrigins struct {
	origin    string
	originCtx string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmLock *mLockerMockLock) Optional() *mLockerMockLock {
	mmLock.optional = true
	return mmLock
}

// Expect sets up expected params for Locker.Lock
func (mmLock *mLockerMockLock) Expect(ctx context.Context) *mLockerMockLock {
	if mmLock.mock.funcLock != nil {
		mmLock.mock.t.Fatalf("LockerMock.Lock mock is already set by Set")
	}

	if mmLock.defaultExpectation == nil {
		mmLock.defaultExpectation = &LockerMockLockExpectation{}
	}

	if mmLock.defaultExpectation.paramPtrs != nil {
		mmLock.mock.t.Fatalf("LockerMock.Lock mock is already set by ExpectParams functions")
	}

	mmLock.defaultExpectation.params = &LockerMockLockParams{ctx}
	mmLock.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmLock.expectations {
		if minimock.Equal(e.params, mmLock.defaultExpectation.params) {
			mmLock.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmLock.defaultExpectation.params)
		}
	}

	return mmLock
}

// ExpectCtxParam1 sets up expected param ctx for Locker.Lock
func (mmLock *mLockerMockLock) ExpectCtxParam1(ctx context.Context) *mLockerMockLock {
	if mmLock.mock.funcLock != nil {
		mmLock.mock.t.Fatalf("LockerMock.Lock mock is already set by Set")
	}

	if mmLock.defaultExpectation == nil {
		mmLock.defaultExpectation = &LockerMockLockExpectation{}
	}

	if mmLock.defaultExpectation.params != nil {
		mmLock.mock.t.Fatalf("LockerMock.Lock mock is already set by Expect")
	}

	if mmLock.defaultExpectation.paramPtrs == nil {
		mmLock.defaultExpectation.paramPtrs = &LockerMockLockParamPtrs{}
	}
	mmLock.defaultExpectation.paramPtrs.ctx = &ctx
	mmLock.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmLock
}

// Inspect accepts an inspector function that has same arguments as the Locker.Lock
func (mmLock *mLockerMockLock) Inspect(f func(ctx context.Context)) *mLockerMockLock {
	if mmLock.mock.inspectFuncLock != nil {
		mmLock.mock.t.Fatalf("Inspect function is already set for LockerMock.Lock")
	}

	mmLock.mock.inspectFuncLock = f

	return mmLock
}

// Return sets up results that will be returned by Locker.Lock
func (mmLock *mLockerMockLock) Return(err error) *LockerMock {
	if mmLock.mock.funcLock != nil {
		mmLock.mock.t.Fatalf("LockerMock.Lock mock is already set by Set")
	}

	if mmLock.defaultExpectation == nil {
		mmLock.defaultExpectation = &LockerMockLockExpectation{mock: mmLock.mock}
	}
	mmLock.defaultExpectation.results = &LockerMockLockResults{err}
	mmLock.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmLock.mock
}

// Set uses given function f to mock the Locker.Lock method
func (mmLock *mLockerMockLock) Set(f func(ctx context.Context) (err error)) *LockerMock {
	if mmLock.defaultExpectation != nil {
		mmLock.mock.t.Fatalf("Default expectation is already set for the Locker.Lock method")
	}

	if len(mmLock.expectations) > 0 {
		mmLock.mock.t.Fatalf("Some expectations are already set for the Locker.Lock method")
	}

	mmLock.mock.funcLock = f
	mmLock.mock.funcLockOrigin = minimock.CallerInfo(1)
	return mmLock.mock
}

// When sets expectation for the Locker.Lock which will trigger the result defined by the following
// Then helper
func (mmLock *mLockerMockLock) When(ctx context.Context) *LockerMockLockExpectation {
	if mmLock.mock.funcLock != nil {
		mmLock.mock.t.Fatalf("LockerMock.Lock mock is already set by Set")
	}

	expectation := &LockerMockLockExpectation{
		mock:               mmLock.mock,
		params:             &LockerMockLockParams{ctx},
		expectationOrigins: LockerMockLockExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmLock.expectations = append(mmLock.expectations, expectation)
	return expectation
}

// Then sets up Locker.Lock return parameters for the expectation previously defined by the When method
func (e *LockerMockLockExpectation) Then(err error) *LockerMock {
	e.results = &LockerMockLockResults{err}
	return e.mock
}

// Times sets number of times Locker.Lock should be invoked
func (mmLock *mLockerMockLock) Times(n uint64) *mLockerMockLock {
	if n == 0 {
		mmLock.mock.t.Fatalf("Times of LockerMock.Lock mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmLock.expectedInvocations, n)
	mmLock.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmLock
}

func (mmLock *mLockerMockLock) invocationsDone() bool {
	if len(mmLock.expectations) == 0 && mmLock.defaultExpectation == nil && mmLock.mock.funcLock == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmLock.mock.afterLockCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmLock.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Lock implements mm_locker.Locker
func (mmLock *LockerMock) Lock(ctx context.Context) (err error) {
	mm_atomic.AddUint64(&mmLock.beforeLockCounter, 1)
	defer mm_atomic.AddUint64(&mmLock.afterLockCounter, 1)

	mmLock.t.Helper()

	if mmLock.inspectFuncLock != nil {
		mmLock.inspectFuncLock(ctx)
	}

	mm_params := LockerMockLockParams{ctx}

	// Record call args
	mmLock.LockMock.mutex.Lock()
	mmLock.LockMock.callArgs = append(mmLock.LockMock.callArgs, &mm_params)
	mmLock.LockMock.mutex.Unlock()

	for _, e := range mmLock.LockMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmLock.LockMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmLock.LockMock.defaultExpectation.Counter, 1)
		mm_want := mmLock.LockMock.defaultExpectation.params
		mm_want_ptrs := mmLock.LockMock.defaultExpectation.paramPtrs

		mm_got := LockerMockLockParams{ctx}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmLock.t.Errorf("LockerMock.Lock got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmLock.LockMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmLock.t.Errorf("LockerMock.Lock got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmLock.LockMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmLock.LockMock.defaultExpectation.results
		if mm_results == nil {
			mmLock.t.Fatal("No results are set for the LockerMock.Lock")
		}
		return (*mm_results).err
	}
	if mmLock.funcLock != nil {
		return mmLock.funcLock(ctx)
	}
	mmLock.t.Fatalf("Unexpected call to LockerMock.Lock. %v", ctx)
	return
}

// LockAfterCounter returns a count of finished LockerMock.Lock invocations
func (mmLock *LockerMock) LockAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmLock.afterLockCounter)
}

// LockBeforeCounter returns a count of LockerMock.Lock invocations
func (mmLock *LockerMock) LockBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmLock.beforeLockCounter)
}

// Calls returns a list of arguments used in each call to LockerMock.Lock.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmLock *mLockerMockLock) Calls() []*LockerMockLockParams {
	mmLock.mutex.RLock()

	argCopy := make([]*LockerMockLockParams, len(mmLock.callArgs))
	copy(argCopy, mmLock.callArgs)

	mmLock.mutex.RUnlock()

	return argCopy
}

// MinimockLockDone returns true if the count of the Lock invocations corresponds
// the number of defined expectations
func (m *LockerMock) MinimockLockDone() bool {
	if m.LockMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.LockMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.LockMock.invocationsDone()
}

// MinimockLockInspect logs each unmet expectation
func (m *LockerMock) MinimockLockInspect() {
	for _, e := range m.LockMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LockerMock.Lock at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterLockCounter := mm_atomic.LoadUint64(&m.afterLockCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.LockMock.defaultExpectation != nil && afterLockCounter < 1 {
		if m.LockMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LockerMock.Lock at\n%s", m.LockMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LockerMock.Lock at\n%s with params: %#v", m.LockMock.defaultExpectation.expectationOrigins.origin, *m.LockMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcLock != nil && afterLockCounter < 1 {
		m.t.Errorf("Expected call to LockerMock.Lock at\n%s", m.funcLockOrigin)
	}

	if !m.LockMock.invocationsDone() && afterLockCounter > 0 {
		m.t.Errorf("Expected %d calls to LockerMock.Lock at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.LockMock.expectedInvocations), m.LockMock.expectedInvocationsOrigin, afterLockCounter)
	}
}

type mLockerMockTryLock struct {
	optional           bool
	mock               *LockerMock
	defaultExpectation *LockerMockTryLockExpectation
	expectations       []*LockerMockTryLockExpectation

	callArgs []*LockerMockTryLockParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LockerMockTryLockExpectation specifies expectation struct of the Locker.TryLock
type LockerMockTryLockExpectation struct {
	mock               *LockerMock
	params             *LockerMockTryLockParams
	paramPtrs          *LockerMockTryLockParamPtrs
	expectationOrigins LockerMockTryLockExpectationOrigins
	results            *LockerMockTryLockResults
	returnOrigin       string
	Counter            uint64
}

// LockerMockTryLockParams contains parameters of the Locker.TryLock
type LockerMockTryLockParams struct {
	ctx context.Context
}

// LockerMockTryLockParamPtrs contains pointers to parameters of the Locker.TryLock
type LockerMockTryLockParamPtrs struct {
	ctx *context.Context
}

// LockerMockTryLockResults contains results of the Locker.TryLock
type LockerMockTryLockResults struct {
	err error
}

// LockerMockTryLockOrigins contains origins of expectations of the Locker.TryLock
type LockerMockTryLockExpectationOrigins struct {
	origin    string
	originCtx string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmTryLock *mLockerMockTryLock) Optional() *mLockerMockTryLock {
	mmTryLock.optional = true
	return mmTryLock
}

// Expect sets up expected params for Locker.TryLock
func (mmTryLock *mLockerMockTryLock) Expect(ctx context.Context) *mLockerMockTryLock {
	if mmTryLock.mock.funcTryLock != nil {
		mmTryLock.mock.t.Fatalf("LockerMock.TryLock mock is already set by Set")
	}

	if mmTryLock.defaultExpectation == nil {
		mmTryLock.defaultExpectation = &LockerMockTryLockExpectation{}
	}

	if mmTryLock.defaultExpectation.paramPtrs != nil {
		mmTryLock.mock.t.Fatalf("LockerMock.TryLock mock is already set by ExpectParams functions")
	}

	mmTryLock.defaultExpectation.params = &LockerMockTryLockParams{ctx}
	mmTryLock.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmTryLock.expectations {
		if minimock.Equal(e.params, mmTryLock.defaultExpectation.params) {
			mmTryLock.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmTryLock.defaultExpectation.params)
		}
	}

	return mmTryLock
}

// ExpectCtxParam1 sets up expected param ctx for Locker.TryLock
func (mmTryLock *mLockerMockTryLock) ExpectCtxParam1(ctx context.Context) *mLockerMockTryLock {
	if mmTryLock.mock.funcTryLock != nil {
		mmTryLock.mock.t.Fatalf("LockerMock.TryLock mock is already set by Set")
	}

	if mmTryLock.defaultExpectation == nil {
		mmTryLock.defaultExpectation = &LockerMockTryLockExpectation{}
	}

	if mmTryLock.defaultExpectation.params != nil {
		mmTryLock.mock.t.Fatalf("LockerMock.TryLock mock is already set by Expect")
	}

	if mmTryLock.defaultExpectation.paramPtrs == nil {
		mmTryLock.defaultExpectation.paramPtrs = &LockerMockTryLockParamPtrs{}
	}
	mmTryLock.defaultExpectation.paramPtrs.ctx = &ctx
	mmTryLock.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmTryLock
}

// Inspect accepts an inspector function that has same arguments as the Locker.TryLock
func (mmTryLock *mLockerMockTryLock) Inspect(f func(ctx context.Context)) *mLockerMockTryLock {
	if mmTryLock.mock.inspectFuncTryLock != nil {
		mmTryLock.mock.t.Fatalf("Inspect function is already set for LockerMock.TryLock")
	}

	mmTryLock.mock.inspectFuncTryLock = f

	return mmTryLock
}

// Return sets up results that will be returned by Locker.TryLock
func (mmTryLock *mLockerMockTryLock) Return(err error) *LockerMock {
	if mmTryLock.mock.funcTryLock != nil {
		mmTryLock.mock.t.Fatalf("LockerMock.TryLock mock is already set by Set")
	}

	if mmTryLock.defaultExpectation == nil {
		mmTryLock.defaultExpectation = &LockerMockTryLockExpectation{mock: mmTryLock.mock}
	}
	mmTryLock.defaultExpectation.results = &LockerMockTryLockResults{err}
	mmTryLock.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmTryLock.mock
}

// Set uses given function f to mock the Locker.TryLock method
func (mmTryLock *mLockerMockTryLock) Set(f func(ctx context.Context) (err error)) *LockerMock {
	if mmTryLock.defaultExpectation != nil {
		mmTryLock.mock.t.Fatalf("Default expectation is already set for the Locker.TryLock method")
	}

	if len(mmTryLock.expectations) > 0 {
		mmTryLock.mock.t.Fatalf("Some expectations are already set for the Locker.TryLock method")
	}

	mmTryLock.mock.funcTryLock = f
	mmTryLock.mock.funcTryLockOrigin = minimock.CallerInfo(1)
	return mmTryLock.mock
}

// When sets expectation for the Locker.TryLock which will trigger the result defined by the following
// Then helper
func (mmTryLock *mLockerMockTryLock) When(ctx context.Context) *LockerMockTryLockExpectation {
	if mmTryLock.mock.funcTryLock != nil {
		mmTryLock.mock.t.Fatalf("LockerMock.TryLock mock is already set by Set")
	}

	expectation := &LockerMockTryLockExpectation{
		mock:               mmTryLock.mock,
		params:             &LockerMockTryLockParams{ctx},
		expectationOrigins: LockerMockTryLockExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmTryLock.expectations = append(mmTryLock.expectations, expectation)
	return expectation
}

// Then sets up Locker.TryLock return parameters for the expectation previously defined by the When method
func (e *LockerMockTryLockExpectation) Then(err error) *LockerMock {
	e.results = &LockerMockTryLockResults{err}
	return e.mock
}

// Times sets number of times Locker.TryLock should be invoked
func (mmTryLock *mLockerMockTryLock) Times(n uint64) *mLockerMockTryLock {
	if n == 0 {
		mmTryLock.mock.t.Fatalf("Times of LockerMock.TryLock mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmTryLock.expectedInvocations, n)
	mmTryLock.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmTryLock
}

func (mmTryLock *mLockerMockTryLock) invocationsDone() bool {
	if len(mmTryLock.expectations) == 0 && mmTryLock.defaultExpectation == nil && mmTryLock.mock.funcTryLock == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmTryLock.mock.afterTryLockCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmTryLock.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// TryLock implements mm_locker.Locker
func (mmTryLock *LockerMock) TryLock(ctx context.Context) (err error) {
	mm_atomic.AddUint64(&mmTryLock.beforeTryLockCounter, 1)
	defer mm_atomic.AddUint64(&mmTryLock.afterTryLockCounter, 1)

	mmTryLock.t.Helper()

	if mmTryLock.inspectFuncTryLock != nil {
		mmTryLock.inspectFuncTryLock(ctx)
	}

	mm_params := LockerMockTryLockParams{ctx}

	// Record call args
	mmTryLock.TryLockMock.mutex.Lock()
	mmTryLock.TryLockMock.callArgs = append(mmTryLock.TryLockMock.callArgs, &mm_params)
	mmTryLock.TryLockMock.mutex.Unlock()

	for _, e := range mmTryLock.TryLockMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmTryLock.TryLockMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmTryLock.TryLockMock.defaultExpectation.Counter, 1)
		mm_want := mmTryLock.TryLockMock.defaultExpectation.params
		mm_want_ptrs := mmTryLock.TryLockMock.defaultExpectation.paramPtrs

		mm_got := LockerMockTryLockParams{ctx}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmTryLock.t.Errorf("LockerMock.TryLock got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmTryLock.TryLockMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmTryLock.t.Errorf("LockerMock.TryLock got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmTryLock.TryLockMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmTryLock.TryLockMock.defaultExpectation.results
		if mm_results == nil {
			mmTryLock.t.Fatal("No results are set for the LockerMock.TryLock")
		}
		return (*mm_results).err
	}
	if mmTryLock.funcTryLock != nil {
		return mmTryLock.funcTryLock(ctx)
	}
	mmTryLock.t.Fatalf("Unexpected call to LockerMock.TryLock. %v", ctx)
	return
}

// TryLockAfterCounter returns a count of finished LockerMock.TryLock invocations
func (mmTryLock *LockerMock) TryLockAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmTryLock.afterTryLockCounter)
}

// TryLockBeforeCounter returns a count of LockerMock.TryLock invocations
func (mmTryLock *LockerMock) TryLockBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmTryLock.beforeTryLockCounter)
}

// Calls returns a list of arguments used in each call to LockerMock.TryLock.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmTryLock *mLockerMockTryLock) Calls() []*LockerMockTryLockParams {
	mmTryLock.mutex.RLock()

	argCopy := make([]*LockerMockTryLockParams, len(mmTryLock.callArgs))
	copy(argCopy, mmTryLock.callArgs)

	mmTryLock.mutex.RUnlock()

	return argCopy
}

// MinimockTryLockDone returns true if the count of the TryLock invocations corresponds
// the number of defined expectations
func (m *LockerMock) MinimockTryLockDone() bool {
	if m.TryLockMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.TryLockMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.TryLockMock.invocationsDone()
}

// MinimockTryLockInspect logs each unmet expectation
func (m *LockerMock) MinimockTryLockInspect() {
	for _, e := range m.TryLockMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LockerMock.TryLock at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterTryLockCounter := mm_atomic.LoadUint64(&m.afterTryLockCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.TryLockMock.defaultExpectation != nil && afterTryLockCounter < 1 {
		if m.TryLockMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LockerMock.TryLock at\n%s", m.TryLockMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LockerMock.TryLock at\n%s with params: %#v", m.TryLockMock.defaultExpectation.expectationOrigins.origin, *m.TryLockMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcTryLock != nil && afterTryLockCounter < 1 {
		m.t.Errorf("Expected call to LockerMock.TryLock at\n%s", m.funcTryLockOrigin)
	}

	if !m.TryLockMock.invocationsDone() && afterTryLockCounter > 0 {
		m.t.Errorf("Expected %d calls to LockerMock.TryLock at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.TryLockMock.expectedInvocations), m.TryLockMock.expectedInvocationsOrigin, afterTryLockCounter)
	}
}

type mLockerMockUnlock struct {
	optional           bool
	mock               *LockerMock
	defaultExpectation *LockerMockUnlockExpectation
	expectations       []*LockerMockUnlockExpectation

	callArgs []*LockerMockUnlockParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LockerMockUnlockExpectation specifies expectation struct of the Locker.Unlock
type LockerMockUnlockExpectation struct {
	mock               *LockerMock
	params             *LockerMockUnlockParams
	paramPtrs          *LockerMockUnlockParamPtrs
	expectationOrigins LockerMockUnlockExpectationOrigins
	results            *LockerMockUnlockResults
	returnOrigin       string
	Counter            uint64
}

// LockerMockUnlockParams contains parameters of the Locker.Unlock
type LockerMockUnlockParams struct {
	ctx context.Context
}

// LockerMockUnlockParamPtrs contains pointers to parameters of the Locker.Unlock
type LockerMockUnlockParamPtrs struct {
	ctx *context.Context
}

// LockerMockUnlockResults contains results of the Locker.Unlock
type LockerMockUnlockResults struct {
	err error
}

// LockerMockUnlockOrigins contains origins of expectations of the Locker.Unlock
type LockerMockUnlockExpectationOrigins struct {
	origin    string
	originCtx string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmUnlock *mLockerMockUnlock) Optional() *mLockerMockUnlock {
	mmUnlock.optional = true
	return mmUnlock
}

// Expect sets up expected params for Locker.Unlock
func (mmUnlock *mLockerMockUnlock) Expect(ctx context.Context) *mLockerMockUnlock {
	if mmUnlock.mock.funcUnlock != nil {
		mmUnlock.mock.t.Fatalf("LockerMock.Unlock mock is already set by Set")
	}

	if mmUnlock.defaultExpectation == nil {
		mmUnlock.defaultExpectation = &LockerMockUnlockExpectation{}
	}

	if mmUnlock.defaultExpectation.paramPtrs != nil {
		mmUnlock.mock.t.Fatalf("LockerMock.Unlock mock is already set by ExpectParams functions")
	}

	mmUnlock.defaultExpectation.params = &LockerMockUnlockParams{ctx}
	mmUnlock.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmUnlock.expectations {
		if minimock.Equal(e.params, mmUnlock.defaultExpectation.params) {
			mmUnlock.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUnlock.defaultExpectation.params)
		}
	}

	return mmUnlock
}

// ExpectCtxParam1 sets up expected param ctx for Locker.Unlock
func (mmUnlock *mLockerMockUnlock) ExpectCtxParam1(ctx context.Context) *mLockerMockUnlock {
	if mmUnlock.mock.funcUnlock != nil {
		mmUnlock.mock.t.Fatalf("LockerMock.Unlock mock is already set by Set")
	}

	if mmUnlock.defaultExpectation == nil {
		mmUnlock.defaultExpectation = &LockerMockUnlockExpectation{}
	}

	if mmUnlock.defaultExpectation.params != nil {
		mmUnlock.mock.t.Fatalf("LockerMock.Unlock mock is already set by Expect")
	}

	if mmUnlock.defaultExpectation.paramPtrs == nil {
		mmUnlock.defaultExpectation.paramPtrs = &LockerMockUnlockParamPtrs{}
	}
	mmUnlock.defaultExpectation.paramPtrs.ctx = &ctx
	mmUnlock.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmUnlock
}

// Inspect accepts an inspector function that has same arguments as the Locker.Unlock
func (mmUnlock *mLockerMockUnlock) Inspect(f func(ctx context.Context)) *mLockerMockUnlock {
	if mmUnlock.mock.inspectFuncUnlock != nil {
		mmUnlock.mock.t.Fatalf("Inspect function is already set for LockerMock.Unlock")
	}

	mmUnlock.mock.inspectFuncUnlock = f

	return mmUnlock
}

// Return sets up results that will be returned by Locker.Unlock
func (mmUnlock *mLockerMockUnlock) Return(err error) *LockerMock {
	if mmUnlock.mock.funcUnlock != nil {
		mmUnlock.mock.t.Fatalf("LockerMock.Unlock mock is already set by Set")
	}

	if mmUnlock.defaultExpectation == nil {
		mmUnlock.defaultExpectation = &LockerMockUnlockExpectation{mock: mmUnlock.mock}
	}
	mmUnlock.defaultExpectation.results = &LockerMockUnlockResults{err}
	mmUnlock.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmUnlock.mock
}

// Set uses given function f to mock the Locker.Unlock method
func (mmUnlock *mLockerMockUnlock) Set(f func(ctx context.Context) (err error)) *LockerMock {
	if mmUnlock.defaultExpectation != nil {
		mmUnlock.mock.t.Fatalf("Default expectation is already set for the Locker.Unlock method")
	}

	if len(mmUnlock.expectations) > 0 {
		mmUnlock.mock.t.Fatalf("Some expectations are already set for the Locker.Unlock method")
	}

	mmUnlock.mock.funcUnlock = f
	mmUnlock.mock.funcUnlockOrigin = minimock.CallerInfo(1)
	return mmUnlock.mock
}

// When sets expectation for the Locker.Unlock which will trigger the result defined by the following
// Then helper
func (mmUnlock *mLockerMockUnlock) When(ctx context.Context) *LockerMockUnlockExpectation {
	if mmUnlock.mock.funcUnlock != nil {
		mmUnlock.mock.t.Fatalf("LockerMock.Unlock mock is already set by Set")
	}

	expectation := &LockerMockUnlockExpectation{
		mock:               mmUnlock.mock,
		params:             &LockerMockUnlockParams{ctx},
		expectationOrigins: LockerMockUnlockExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmUnlock.expectations = append(mmUnlock.expectations, expectation)
	return expectation
}

// Then sets up Locker.Unlock return parameters for the expectation previously defined by the When method
func (e *LockerMockUnlockExpectation) Then(err error) *LockerMock {
	e.results = &LockerMockUnlockResults{err}
	return e.mock
}

// Times sets number of times Locker.Unlock should be invoked
func (mmUnlock *mLockerMockUnlock) Times(n uint64) *mLockerMockUnlock {
	if n == 0 {
		mmUnlock.mock.t.Fatalf("Times of LockerMock.Unlock mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmUnlock.expectedInvocations, n)
	mmUnlock.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmUnlock
}

func (mmUnlock *mLockerMockUnlock) invocationsDone() bool {
	if len(mmUnlock.expectations) == 0 && mmUnlock.defaultExpectation == nil && mmUnlock.mock.funcUnlock == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmUnlock.mock.afterUnlockCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmUnlock.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Unlock implements mm_locker.Locker
func (mmUnlock *LockerMock) Unlock(ctx context.Context) (err error) {
	mm_atomic.AddUint64(&mmUnlock.beforeUnlockCounter, 1)
	defer mm_atomic.AddUint64(&mmUnlock.afterUnlockCounter, 1)

	mmUnlock.t.Helper()

	if mmUnlock.inspectFuncUnlock != nil {
		mmUnlock.inspectFuncUnlock(ctx)
	}

	mm_params := LockerMockUnlockParams{ctx}

	// Record call args
	mmUnlock.UnlockMock.mutex.Lock()
	mmUnlock.UnlockMock.callArgs = append(mmUnlock.UnlockMock.callArgs, &mm_params)
	mmUnlock.UnlockMock.mutex.Unlock()

	for _, e := range mmUnlock.UnlockMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmUnlock.UnlockMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUnlock.UnlockMock.defaultExpectation.Counter, 1)
		mm_want := mmUnlock.UnlockMock.defaultExpectation.params
		mm_want_ptrs := mmUnlock.UnlockMock.defaultExpectation.paramPtrs

		mm_got := LockerMockUnlockParams{ctx}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmUnlock.t.Errorf("LockerMock.Unlock got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUnlock.UnlockMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUnlock.t.Errorf("LockerMock.Unlock got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmUnlock.UnlockMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUnlock.UnlockMock.defaultExpectation.results
		if mm_results == nil {
			mmUnlock.t.Fatal("No results are set for the LockerMock.Unlock")
		}
		return (*mm_results).err
	}
	if mmUnlock.funcUnlock != nil {
		return mmUnlock.funcUnlock(ctx)
	}
	mmUnlock.t.Fatalf("Unexpected call to LockerMock.Unlock. %v", ctx)
	return
}

// UnlockAfterCounter returns a count of finished LockerMock.Unlock invocations
func (mmUnlock *LockerMock) UnlockAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUnlock.afterUnlockCounter)
}

// UnlockBeforeCounter returns a count of LockerMock.Unlock invocations
func (mmUnlock *LockerMock) UnlockBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUnlock.beforeUnlockCounter)
}

// Calls returns a list of arguments used in each call to LockerMock.Unlock.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUnlock *mLockerMockUnlock) Calls() []*LockerMockUnlockParams {
	mmUnlock.mutex.RLock()

	argCopy := make([]*LockerMockUnlockParams, len(mmUnlock.callArgs))
	copy(argCopy, mmUnlock.callArgs)

	mmUnlock.mutex.RUnlock()

	return argCopy
}

// MinimockUnlockDone returns true if the count of the Unlock invocations corresponds
// the number of defined expectations
func (m *LockerMock) MinimockUnlockDone() bool {
	if m.UnlockMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.UnlockMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.UnlockMock.invocationsDone()
}

// MinimockUnlockInspect logs each unmet expectation
func (m *LockerMock) MinimockUnlockInspect() {
	for _, e := range m.UnlockMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LockerMock.Unlock at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterUnlockCounter := mm_atomic.LoadUint64(&m.afterUnlockCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.UnlockMock.defaultExpectation != nil && afterUnlockCounter < 1 {
		if m.UnlockMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LockerMock.Unlock at\n%s", m.UnlockMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LockerMock.Unlock at\n%s with params: %#v", m.UnlockMock.defaultExpectation.expectationOrigins.origin, *m.UnlockMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUnlock != nil && afterUnlockCounter < 1 {
		m.t.Errorf("Expected call to LockerMock.Unlock at\n%s", m.funcUnlockOrigin)
	}

	if !m.UnlockMock.invocationsDone() && afterUnlockCounter > 0 {
		m.t.Errorf("Expected %d calls to LockerMock.Unlock at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.UnlockMock.expectedInvocations), m.UnlockMock.expectedInvocationsOrigin, afterUnlockCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *LockerMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockKeyInspect()

			m.MinimockLockInspect()

			m.MinimockTryLockInspect()

			m.MinimockUnlockInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *LockerMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *LockerMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockKeyDone() &&
		m.MinimockLockDone() &&
		m.MinimockTryLockDone() &&
		m.MinimockUnlockDone()
}
