// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/tarantool/go-tarantool/v3"
)

// TCSClientMock implements mm_tcs.Client
type TCSClientMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcDo          func(req tarantool.Request) (fut tarantool.Future)
	funcDoOrigin    string
	inspectFuncDo   func(req tarantool.Request)
	afterDoCounter  uint64
	beforeDoCounter uint64
	DoMock          mTCSClientMockDo

	funcNewWatcher          func(key string, callback tarantool.WatchCallback) (w1 tarantool.Watcher, err error)
	funcNewWatcherOrigin    string
	inspectFuncNewWatcher   func(key string, callback tarantool.WatchCallback)
	afterNewWatcherCounter  uint64
	beforeNewWatcherCounter uint64
	NewWatcherMock          mTCSClientMockNewWatcher
}

// NewTCSClientMock returns a mock for mm_tcs.Client
func NewTCSClientMock(t minimock.Tester) *TCSClientMock {
	m := &TCSClientMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.DoMock = mTCSClientMockDo{mock: m}
	m.DoMock.callArgs = []*TCSClientMockDoParams{}

	m.NewWatcherMock = mTCSClientMockNewWatcher{mock: m}
	m.NewWatcherMock.callArgs = []*TCSClientMockNewWatcherParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mTCSClientMockDo struct {
	optional           bool
	mock               *TCSClientMock
	defaultExpectation *TCSClientMockDoExpectation
	expectations       []*TCSClientMockDoExpectation

	callArgs []*TCSClientMockDoParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// TCSClientMockDoExpectation specifies expectation struct of the Client.Do
type TCSClientMockDoExpectation struct {
	mock               *TCSClientMock
	params             *TCSClientMockDoParams
	paramPtrs          *TCSClientMockDoParamPtrs
	expectationOrigins TCSClientMockDoExpectationOrigins
	results            *TCSClientMockDoResults
	returnOrigin       string
	Counter            uint64
}

// TCSClientMockDoParams contains parameters of the Client.Do
type TCSClientMockDoParams struct {
	req tarantool.Request
}

// TCSClientMockDoParamPtrs contains pointers to parameters of the Client.Do
type TCSClientMockDoParamPtrs struct {
	req *tarantool.Request
}

// TCSClientMockDoResults contains results of the Client.Do
type TCSClientMockDoResults struct {
	fut tarantool.Future
}

// TCSClientMockDoOrigins contains origins of expectations of the Client.Do
type TCSClientMockDoExpectationOrigins struct {
	origin    string
	originReq string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDo *mTCSClientMockDo) Optional() *mTCSClientMockDo {
	mmDo.optional = true
	return mmDo
}

// Expect sets up expected params for Client.Do
func (mmDo *mTCSClientMockDo) Expect(req tarantool.Request) *mTCSClientMockDo {
	if mmDo.mock.funcDo != nil {
		mmDo.mock.t.Fatalf("TCSClientMock.Do mock is already set by Set")
	}

	if mmDo.defaultExpectation == nil {
		mmDo.defaultExpectation = &TCSClientMockDoExpectation{}
	}

	if mmDo.defaultExpectation.paramPtrs != nil {
		mmDo.mock.t.Fatalf("TCSClientMock.Do mock is already set by ExpectParams functions")
	}

	mmDo.defaultExpectation.params = &TCSClientMockDoParams{req}
	mmDo.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDo.expectations {
		if minimock.Equal(e.params, mmDo.defaultExpectation.params) {
			mmDo.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDo.defaultExpectation.params)
		}
	}

	return mmDo
}

// ExpectReqParam1 sets up expected param req for Client.Do
func (mmDo *mTCSClientMockDo) ExpectReqParam1(req tarantool.Request) *mTCSClientMockDo {
	if mmDo.mock.funcDo != nil {
		mmDo.mock.t.Fatalf("TCSClientMock.Do mock is already set by Set")
	}

	if mmDo.defaultExpectation == nil {
		mmDo.defaultExpectation = &TCSClientMockDoExpectation{}
	}

	if mmDo.defaultExpectation.params != nil {
		mmDo.mock.t.Fatalf("TCSClientMock.Do mock is already set by Expect")
	}

	if mmDo.defaultExpectation.paramPtrs == nil {
		mmDo.defaultExpectation.paramPtrs = &TCSClientMockDoParamPtrs{}
	}
	mmDo.defaultExpectation.paramPtrs.req = &req
	mmDo.defaultExpectation.expectationOrigins.originReq = minimock.CallerInfo(1)

	return mmDo
}

// Inspect accepts an inspector function that has same arguments as the Client.Do
func (mmDo *mTCSClientMockDo) Inspect(f func(req tarantool.Request)) *mTCSClientMockDo {
	if mmDo.mock.inspectFuncDo != nil {
		mmDo.mock.t.Fatalf("Inspect function is already set for TCSClientMock.Do")
	}

	mmDo.mock.inspectFuncDo = f

	return mmDo
}

// Return sets up results that will be returned by Client.Do
func (mmDo *mTCSClientMockDo) Return(fut tarantool.Future) *TCSClientMock {
	if mmDo.mock.funcDo != nil {
		mmDo.mock.t.Fatalf("TCSClientMock.Do mock is already set by Set")
	}

	if mmDo.defaultExpectation == nil {
		mmDo.defaultExpectation = &TCSClientMockDoExpectation{mock: mmDo.mock}
	}
	mmDo.defaultExpectation.results = &TCSClientMockDoResults{fut}
	mmDo.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDo.mock
}

// Set uses given function f to mock the Client.Do method
func (mmDo *mTCSClientMockDo) Set(f func(req tarantool.Request) (fut tarantool.Future)) *TCSClientMock {
	if mmDo.defaultExpectation != nil {
		mmDo.mock.t.Fatalf("Default expectation is already set for the Client.Do method")
	}

	if len(mmDo.expectations) > 0 {
		mmDo.mock.t.Fatalf("Some expectations are already set for the Client.Do method")
	}

	mmDo.mock.funcDo = f
	mmDo.mock.funcDoOrigin = minimock.CallerInfo(1)
	return mmDo.mock
}

// When sets expectation for the Client.Do which will trigger the result defined by the following
// Then helper
func (mmDo *mTCSClientMockDo) When(req tarantool.Request) *TCSClientMockDoExpectation {
	if mmDo.mock.funcDo != nil {
		mmDo.mock.t.Fatalf("TCSClientMock.Do mock is already set by Set")
	}

	expectation := &TCSClientMockDoExpectation{
		mock:               mmDo.mock,
		params:             &TCSClientMockDoParams{req},
		expectationOrigins: TCSClientMockDoExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDo.expectations = append(mmDo.expectations, expectation)
	return expectation
}

// Then sets up Client.Do return parameters for the expectation previously defined by the When method
func (e *TCSClientMockDoExpectation) Then(fut tarantool.Future) *TCSClientMock {
	e.results = &TCSClientMockDoResults{fut}
	return e.mock
}

// Times sets number of times Client.Do should be invoked
func (mmDo *mTCSClientMockDo) Times(n uint64) *mTCSClientMockDo {
	if n == 0 {
		mmDo.mock.t.Fatalf("Times of TCSClientMock.Do mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDo.expectedInvocations, n)
	mmDo.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDo
}

func (mmDo *mTCSClientMockDo) invocationsDone() bool {
	if len(mmDo.expectations) == 0 && mmDo.defaultExpectation == nil && mmDo.mock.funcDo == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDo.mock.afterDoCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDo.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Do implements mm_tcs.Client
func (mmDo *TCSClientMock) Do(req tarantool.Request) (fut tarantool.Future) {
	mm_atomic.AddUint64(&mmDo.beforeDoCounter, 1)
	defer mm_atomic.AddUint64(&mmDo.afterDoCounter, 1)

	mmDo.t.Helper()

	if mmDo.inspectFuncDo != nil {
		mmDo.inspectFuncDo(req)
	}

	mm_params := TCSClientMockDoParams{req}

	// Record call args
	mmDo.DoMock.mutex.Lock()
	mmDo.DoMock.callArgs = append(mmDo.DoMock.callArgs, &mm_params)
	mmDo.DoMock.mutex.Unlock()

	for _, e := range mmDo.DoMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.fut
		}
	}

	if mmDo.DoMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDo.DoMock.defaultExpectation.Counter, 1)
		mm_want := mmDo.DoMock.defaultExpectation.params
		mm_want_ptrs := mmDo.DoMock.defaultExpectation.paramPtrs

		mm_got := TCSClientMockDoParams{req}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.req != nil && !minimock.Equal(*mm_want_ptrs.req, mm_got.req) {
				mmDo.t.Errorf("TCSClientMock.Do got unexpected parameter req, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDo.DoMock.defaultExpectation.expectationOrigins.originReq, *mm_want_ptrs.req, mm_got.req, minimock.Diff(*mm_want_ptrs.req, mm_got.req))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDo.t.Errorf("TCSClientMock.Do got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDo.DoMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDo.DoMock.defaultExpectation.results
		if mm_results == nil {
			mmDo.t.Fatal("No results are set for the TCSClientMock.Do")
		}
		return (*mm_results).fut
	}
	if mmDo.funcDo != nil {
		return mmDo.funcDo(req)
	}
	mmDo.t.Fatalf("Unexpected call to TCSClientMock.Do. %v", req)
	return
}

// DoAfterCounter returns a count of finished TCSClientMock.Do invocations
func (mmDo *TCSClientMock) DoAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDo.afterDoCounter)
}

// DoBeforeCounter returns a count of TCSClientMock.Do invocations
func (mmDo *TCSClientMock) DoBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDo.beforeDoCounter)
}

// Calls returns a list of arguments used in each call to TCSClientMock.Do.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDo *mTCSClientMockDo) Calls() []*TCSClientMockDoParams {
	mmDo.mutex.RLock()

	argCopy := make([]*TCSClientMockDoParams, len(mmDo.callArgs))
	copy(argCopy, mmDo.callArgs)

	mmDo.mutex.RUnlock()

	return argCopy
}

// MinimockDoDone returns true if the count of the Do invocations corresponds
// the number of defined expectations
func (m *TCSClientMock) MinimockDoDone() bool {
	if m.DoMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DoMock.invocationsDone()
}

// MinimockDoInspect logs each unmet expectation
func (m *TCSClientMock) MinimockDoInspect() {
	for _, e := range m.DoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to TCSClientMock.Do at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDoCounter := mm_atomic.LoadUint64(&m.afterDoCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DoMock.defaultExpectation != nil && afterDoCounter < 1 {
		if m.DoMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to TCSClientMock.Do at\n%s", m.DoMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to TCSClientMock.Do at\n%s with params: %#v", m.DoMock.defaultExpectation.expectationOrigins.origin, *m.DoMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDo != nil && afterDoCounter < 1 {
		m.t.Errorf("Expected call to TCSClientMock.Do at\n%s", m.funcDoOrigin)
	}

	if !m.DoMock.invocationsDone() && afterDoCounter > 0 {
		m.t.Errorf("Expected %d calls to TCSClientMock.Do at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DoMock.expectedInvocations), m.DoMock.expectedInvocationsOrigin, afterDoCounter)
	}
}

type mTCSClientMockNewWatcher struct {
	optional           bool
	mock               *TCSClientMock
	defaultExpectation *TCSClientMockNewWatcherExpectation
	expectations       []*TCSClientMockNewWatcherExpectation

	callArgs []*TCSClientMockNewWatcherParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// TCSClientMockNewWatcherExpectation specifies expectation struct of the Client.NewWatcher
type TCSClientMockNewWatcherExpectation struct {
	mock               *TCSClientMock
	params             *TCSClientMockNewWatcherParams
	paramPtrs          *TCSClientMockNewWatcherParamPtrs
	expectationOrigins TCSClientMockNewWatcherExpectationOrigins
	results            *TCSClientMockNewWatcherResults
	returnOrigin       string
	Counter            uint64
}

// TCSClientMockNewWatcherParams contains parameters of the Client.NewWatcher
type TCSClientMockNewWatcherParams struct {
	key      string
	callback tarantool.WatchCallback
}

// TCSClientMockNewWatcherParamPtrs contains pointers to parameters of the Client.NewWatcher
type TCSClientMockNewWatcherParamPtrs struct {
	key      *string
	callback *tarantool.WatchCallback
}

// TCSClientMockNewWatcherResults contains results of the Client.NewWatcher
type TCSClientMockNewWatcherResults struct {
	w1  tarantool.Watcher
	err error
}

// TCSClientMockNewWatcherOrigins contains origins of expectations of the Client.NewWatcher
type TCSClientMockNewWatcherExpectationOrigins struct {
	origin         string
	originKey      string
	originCallback string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmNewWatcher *mTCSClientMockNewWatcher) Optional() *mTCSClientMockNewWatcher {
	mmNewWatcher.optional = true
	return mmNewWatcher
}

// Expect sets up expected params for Client.NewWatcher
func (mmNewWatcher *mTCSClientMockNewWatcher) Expect(key string, callback tarantool.WatchCallback) *mTCSClientMockNewWatcher {
	if mmNewWatcher.mock.funcNewWatcher != nil {
		mmNewWatcher.mock.t.Fatalf("TCSClientMock.NewWatcher mock is already set by Set")
	}

	if mmNewWatcher.defaultExpectation == nil {
		mmNewWatcher.defaultExpectation = &TCSClientMockNewWatcherExpectation{}
	}

	if mmNewWatcher.defaultExpectation.paramPtrs != nil {
		mmNewWatcher.mock.t.Fatalf("TCSClientMock.NewWatcher mock is already set by ExpectParams functions")
	}

	mmNewWatcher.defaultExpectation.params = &TCSClientMockNewWatcherParams{key, callback}
	mmNewWatcher.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmNewWatcher.expectations {
		if minimock.Equal(e.params, mmNewWatcher.defaultExpectation.params) {
			mmNewWatcher.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmNewWatcher.defaultExpectation.params)
		}
	}

	return mmNewWatcher
}

// ExpectKeyParam1 sets up expected param key for Client.NewWatcher
func (mmNewWatcher *mTCSClientMockNewWatcher) ExpectKeyParam1(key string) *mTCSClientMockNewWatcher {
	if mmNewWatcher.mock.funcNewWatcher != nil {
		mmNewWatcher.mock.t.Fatalf("TCSClientMock.NewWatcher mock is already set by Set")
	}

	if mmNewWatcher.defaultExpectation == nil {
		mmNewWatcher.defaultExpectation = &TCSClientMockNewWatcherExpectation{}
	}

	if mmNewWatcher.defaultExpectation.params != nil {
		mmNewWatcher.mock.t.Fatalf("TCSClientMock.NewWatcher mock is already set by Expect")
	}

	if mmNewWatcher.defaultExpectation.paramPtrs == nil {
		mmNewWatcher.defaultExpectation.paramPtrs = &TCSClientMockNewWatcherParamPtrs{}
	}
	mmNewWatcher.defaultExpectation.paramPtrs.key = &key
	mmNewWatcher.defaultExpectation.expectationOrigins.originKey = minimock.CallerInfo(1)

	return mmNewWatcher
}

// ExpectCallbackParam2 sets up expected param callback for Client.NewWatcher
func (mmNewWatcher *mTCSClientMockNewWatcher) ExpectCallbackParam2(callback tarantool.WatchCallback) *mTCSClientMockNewWatcher {
	if mmNewWatcher.mock.funcNewWatcher != nil {
		mmNewWatcher.mock.t.Fatalf("TCSClientMock.NewWatcher mock is already set by Set")
	}

	if mmNewWatcher.defaultExpectation == nil {
		mmNewWatcher.defaultExpectation = &TCSClientMockNewWatcherExpectation{}
	}

	if mmNewWatcher.defaultExpectation.params != nil {
		mmNewWatcher.mock.t.Fatalf("TCSClientMock.NewWatcher mock is already set by Expect")
	}

	if mmNewWatcher.defaultExpectation.paramPtrs == nil {
		mmNewWatcher.defaultExpectation.paramPtrs = &TCSClientMockNewWatcherParamPtrs{}
	}
	mmNewWatcher.defaultExpectation.paramPtrs.callback = &callback
	mmNewWatcher.defaultExpectation.expectationOrigins.originCallback = minimock.CallerInfo(1)

	return mmNewWatcher
}

// Inspect accepts an inspector function that has same arguments as the Client.NewWatcher
func (mmNewWatcher *mTCSClientMockNewWatcher) Inspect(f func(key string, callback tarantool.WatchCallback)) *mTCSClientMockNewWatcher {
	if mmNewWatcher.mock.inspectFuncNewWatcher != nil {
		mmNewWatcher.mock.t.Fatalf("Inspect function is already set for TCSClientMock.NewWatcher")
	}

	mmNewWatcher.mock.inspectFuncNewWatcher = f

	return mmNewWatcher
}

// Return sets up results that will be returned by Client.NewWatcher
func (mmNewWatcher *mTCSClientMockNewWatcher) Return(w1 tarantool.Watcher, err error) *TCSClientMock {
	if mmNewWatcher.mock.funcNewWatcher != nil {
		mmNewWatcher.mock.t.Fatalf("TCSClientMock.NewWatcher mock is already set by Set")
	}

	if mmNewWatcher.defaultExpectation == nil {
		mmNewWatcher.defaultExpectation = &TCSClientMockNewWatcherExpectation{mock: mmNewWatcher.mock}
	}
	mmNewWatcher.defaultExpectation.results = &TCSClientMockNewWatcherResults{w1, err}
	mmNewWatcher.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmNewWatcher.mock
}

// Set uses given function f to mock the Client.NewWatcher method
func (mmNewWatcher *mTCSClientMockNewWatcher) Set(f func(key string, callback tarantool.WatchCallback) (w1 tarantool.Watcher, err error)) *TCSClientMock {
	if mmNewWatcher.defaultExpectation != nil {
		mmNewWatcher.mock.t.Fatalf("Default expectation is already set for the Client.NewWatcher method")
	}

	if len(mmNewWatcher.expectations) > 0 {
		mmNewWatcher.mock.t.Fatalf("Some expectations are already set for the Client.NewWatcher method")
	}

	mmNewWatcher.mock.funcNewWatcher = f
	mmNewWatcher.mock.funcNewWatcherOrigin = minimock.CallerInfo(1)
	return mmNewWatcher.mock
}

// When sets expectation for the Client.NewWatcher which will trigger the result defined by the following
// Then helper
func (mmNewWatcher *mTCSClientMockNewWatcher) When(key string, callback tarantool.WatchCallback) *TCSClientMockNewWatcherExpectation {
	if mmNewWatcher.mock.funcNewWatcher != nil {
		mmNewWatcher.mock.t.Fatalf("TCSClientMock.NewWatcher mock is already set by Set")
	}

	expectation := &TCSClientMockNewWatcherExpectation{
		mock:               mmNewWatcher.mock,
		params:             &TCSClientMockNewWatcherParams{key, callback},
		expectationOrigins: TCSClientMockNewWatcherExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmNewWatcher.expectations = append(mmNewWatcher.expectations, expectation)
	return expectation
}

// Then sets up Client.NewWatcher return parameters for the expectation previously defined by the When method
func (e *TCSClientMockNewWatcherExpectation) Then(w1 tarantool.Watcher, err error) *TCSClientMock {
	e.results = &TCSClientMockNewWatcherResults{w1, err}
	return e.mock
}

// Times sets number of times Client.NewWatcher should be invoked
func (mmNewWatcher *mTCSClientMockNewWatcher) Times(n uint64) *mTCSClientMockNewWatcher {
	if n == 0 {
		mmNewWatcher.mock.t.Fatalf("Times of TCSClientMock.NewWatcher mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmNewWatcher.expectedInvocations, n)
	mmNewWatcher.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmNewWatcher
}

func (mmNewWatcher *mTCSClientMockNewWatcher) invocationsDone() bool {
	if len(mmNewWatcher.expectations) == 0 && mmNewWatcher.defaultExpectation == nil && mmNewWatcher.mock.funcNewWatcher == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmNewWatcher.mock.afterNewWatcherCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmNewWatcher.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// NewWatcher implements mm_tcs.Client
func (mmNewWatcher *TCSClientMock) NewWatcher(key string, callback tarantool.WatchCallback) (w1 tarantool.Watcher, err error) {
	mm_atomic.AddUint64(&mmNewWatcher.beforeNewWatcherCounter, 1)
	defer mm_atomic.AddUint64(&mmNewWatcher.afterNewWatcherCounter, 1)

	mmNewWatcher.t.Helper()

	if mmNewWatcher.inspectFuncNewWatcher != nil {
		mmNewWatcher.inspectFuncNewWatcher(key, callback)
	}

	mm_params := TCSClientMockNewWatcherParams{key, callback}

	// Record call args
	mmNewWatcher.NewWatcherMock.mutex.Lock()
	mmNewWatcher.NewWatcherMock.callArgs = append(mmNewWatcher.NewWatcherMock.callArgs, &mm_params)
	mmNewWatcher.NewWatcherMock.mutex.Unlock()

	for _, e := range mmNewWatcher.NewWatcherMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.w1, e.results.err
		}
	}

	if mmNewWatcher.NewWatcherMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmNewWatcher.NewWatcherMock.defaultExpectation.Counter, 1)
		mm_want := mmNewWatcher.NewWatcherMock.defaultExpectation.params
		mm_want_ptrs := mmNewWatcher.NewWatcherMock.defaultExpectation.paramPtrs

		mm_got := TCSClientMockNewWatcherParams{key, callback}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.key != nil && !minimock.Equal(*mm_want_ptrs.key, mm_got.key) {
				mmNewWatcher.t.Errorf("TCSClientMock.NewWatcher got unexpected parameter key, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmNewWatcher.NewWatcherMock.defaultExpectation.expectationOrigins.originKey, *mm_want_ptrs.key, mm_got.key, minimock.Diff(*mm_want_ptrs.key, mm_got.key))
			}

			if mm_want_ptrs.callback != nil && !minimock.Equal(*mm_want_ptrs.callback, mm_got.callback) {
				mmNewWatcher.t.Errorf("TCSClientMock.NewWatcher got unexpected parameter callback, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmNewWatcher.NewWatcherMock.defaultExpectation.expectationOrigins.originCallback, *mm_want_ptrs.callback, mm_got.callback, minimock.Diff(*mm_want_ptrs.callback, mm_got.callback))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmNewWatcher.t.Errorf("TCSClientMock.NewWatcher got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmNewWatcher.NewWatcherMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmNewWatcher.NewWatcherMock.defaultExpectation.results
		if mm_results == nil {
			mmNewWatcher.t.Fatal("No results are set for the TCSClientMock.NewWatcher")
		}
		return (*mm_results).w1, (*mm_results).err
	}
	if mmNewWatcher.funcNewWatcher != nil {
		return mmNewWatcher.funcNewWatcher(key, callback)
	}
	mmNewWatcher.t.Fatalf("Unexpected call to TCSClientMock.NewWatcher. %v %v", key, callback)
	return
}

// NewWatcherAfterCounter returns a count of finished TCSClientMock.NewWatcher invocations
func (mmNewWatcher *TCSClientMock) NewWatcherAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmNewWatcher.afterNewWatcherCounter)
}

// NewWatcherBeforeCounter returns a count of TCSClientMock.NewWatcher invocations
func (mmNewWatcher *TCSClientMock) NewWatcherBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmNewWatcher.beforeNewWatcherCounter)
}

// Calls returns a list of arguments used in each call to TCSClientMock.NewWatcher.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmNewWatcher *mTCSClientMockNewWatcher) Calls() []*TCSClientMockNewWatcherParams {
	mmNewWatcher.mutex.RLock()

	argCopy := make([]*TCSClientMockNewWatcherParams, len(mmNewWatcher.callArgs))
	copy(argCopy, mmNewWatcher.callArgs)

	mmNewWatcher.mutex.RUnlock()

	return argCopy
}

// MinimockNewWatcherDone returns true if the count of the NewWatcher invocations corresponds
// the number of defined expectations
func (m *TCSClientMock) MinimockNewWatcherDone() bool {
	if m.NewWatcherMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.NewWatcherMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.NewWatcherMock.invocationsDone()
}

// MinimockNewWatcherInspect logs each unmet expectation
func (m *TCSClientMock) MinimockNewWatcherInspect() {
	for _, e := range m.NewWatcherMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to TCSClientMock.NewWatcher at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterNewWatcherCounter := mm_atomic.LoadUint64(&m.afterNewWatcherCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.NewWatcherMock.defaultExpectation != nil && afterNewWatcherCounter < 1 {
		if m.NewWatcherMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to TCSClientMock.NewWatcher at\n%s", m.NewWatcherMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to TCSClientMock.NewWatcher at\n%s with params: %#v", m.NewWatcherMock.defaultExpectation.expectationOrigins.origin, *m.NewWatcherMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcNewWatcher != nil && afterNewWatcherCounter < 1 {
		m.t.Errorf("Expected call to TCSClientMock.NewWatcher at\n%s", m.funcNewWatcherOrigin)
	}

	if !m.NewWatcherMock.invocationsDone() && afterNewWatcherCounter > 0 {
		m.t.Errorf("Expected %d calls to TCSClientMock.NewWatcher at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.NewWatcherMock.expectedInvocations), m.NewWatcherMock.expectedInvocationsOrigin, afterNewWatcherCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *TCSClientMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockDoInspect()

			m.MinimockNewWatcherInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *TCSClientMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *TCSClientMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockDoDone() &&
		m.MinimockNewWatcherDone()
}
