// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package storage

//go:generate minimock -i github.com/tarantool/go-storage/v2.Prefixer -o prefixer_mock_test.go -n PrefixerMock -p storage

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// PrefixerMock implements Prefixer
type PrefixerMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcPrefix          func() (ba1 []byte)
	funcPrefixOrigin    string
	inspectFuncPrefix   func()
	afterPrefixCounter  uint64
	beforePrefixCounter uint64
	PrefixMock          mPrefixerMockPrefix
}

// NewPrefixerMock returns a mock for Prefixer
func NewPrefixerMock(t minimock.Tester) *PrefixerMock {
	m := &PrefixerMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.PrefixMock = mPrefixerMockPrefix{mock: m}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mPrefixerMockPrefix struct {
	optional           bool
	mock               *PrefixerMock
	defaultExpectation *PrefixerMockPrefixExpectation
	expectations       []*PrefixerMockPrefixExpectation

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// PrefixerMockPrefixExpectation specifies expectation struct of the Prefixer.Prefix
type PrefixerMockPrefixExpectation struct {
	mock *PrefixerMock

	results      *PrefixerMockPrefixResults
	returnOrigin string
	Counter      uint64
}

// PrefixerMockPrefixResults contains results of the Prefixer.Prefix
type PrefixerMockPrefixResults struct {
	ba1 []byte
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmPrefix *mPrefixerMockPrefix) Optional() *mPrefixerMockPrefix {
	mmPrefix.optional = true
	return mmPrefix
}

// Expect sets up expected params for Prefixer.Prefix
func (mmPrefix *mPrefixerMockPrefix) Expect() *mPrefixerMockPrefix {
	if mmPrefix.mock.funcPrefix != nil {
		mmPrefix.mock.t.Fatalf("PrefixerMock.Prefix mock is already set by Set")
	}

	if mmPrefix.defaultExpectation == nil {
		mmPrefix.defaultExpectation = &PrefixerMockPrefixExpectation{}
	}

	return mmPrefix
}

// Inspect accepts an inspector function that has same arguments as the Prefixer.Prefix
func (mmPrefix *mPrefixerMockPrefix) Inspect(f func()) *mPrefixerMockPrefix {
	if mmPrefix.mock.inspectFuncPrefix != nil {
		mmPrefix.mock.t.Fatalf("Inspect function is already set for PrefixerMock.Prefix")
	}

	mmPrefix.mock.inspectFuncPrefix = f

	return mmPrefix
}

// Return sets up results that will be returned by Prefixer.Prefix
func (mmPrefix *mPrefixerMockPrefix) Return(ba1 []byte) *PrefixerMock {
	if mmPrefix.mock.funcPrefix != nil {
		mmPrefix.mock.t.Fatalf("PrefixerMock.Prefix mock is already set by Set")
	}

	if mmPrefix.defaultExpectation == nil {
		mmPrefix.defaultExpectation = &PrefixerMockPrefixExpectation{mock: mmPrefix.mock}
	}
	mmPrefix.defaultExpectation.results = &PrefixerMockPrefixResults{ba1}
	mmPrefix.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmPrefix.mock
}

// Set uses given function f to mock the Prefixer.Prefix method
func (mmPrefix *mPrefixerMockPrefix) Set(f func() (ba1 []byte)) *PrefixerMock {
	if mmPrefix.defaultExpectation != nil {
		mmPrefix.mock.t.Fatalf("Default expectation is already set for the Prefixer.Prefix method")
	}

	if len(mmPrefix.expectations) > 0 {
		mmPrefix.mock.t.Fatalf("Some expectations are already set for the Prefixer.Prefix method")
	}

	mmPrefix.mock.funcPrefix = f
	mmPrefix.mock.funcPrefixOrigin = minimock.CallerInfo(1)
	return mmPrefix.mock
}

// Times sets number of times Prefixer.Prefix should be invoked
func (mmPrefix *mPrefixerMockPrefix) Times(n uint64) *mPrefixerMockPrefix {
	if n == 0 {
		mmPrefix.mock.t.Fatalf("Times of PrefixerMock.Prefix mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmPrefix.expectedInvocations, n)
	mmPrefix.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmPrefix
}

func (mmPrefix *mPrefixerMockPrefix) invocationsDone() bool {
	if len(mmPrefix.expectations) == 0 && mmPrefix.defaultExpectation == nil && mmPrefix.mock.funcPrefix == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmPrefix.mock.afterPrefixCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmPrefix.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Prefix implements Prefixer
func (mmPrefix *PrefixerMock) Prefix() (ba1 []byte) {
	mm_atomic.AddUint64(&mmPrefix.beforePrefixCounter, 1)
	defer mm_atomic.AddUint64(&mmPrefix.afterPrefixCounter, 1)

	mmPrefix.t.Helper()

	if mmPrefix.inspectFuncPrefix != nil {
		mmPrefix.inspectFuncPrefix()
	}

	if mmPrefix.PrefixMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmPrefix.PrefixMock.defaultExpectation.Counter, 1)

		mm_results := mmPrefix.PrefixMock.defaultExpectation.results
		if mm_results == nil {
			mmPrefix.t.Fatal("No results are set for the PrefixerMock.Prefix")
		}
		return (*mm_results).ba1
	}
	if mmPrefix.funcPrefix != nil {
		return mmPrefix.funcPrefix()
	}
	mmPrefix.t.Fatalf("Unexpected call to PrefixerMock.Prefix.")
	return
}

// PrefixAfterCounter returns a count of finished PrefixerMock.Prefix invocations
func (mmPrefix *PrefixerMock) PrefixAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPrefix.afterPrefixCounter)
}

// PrefixBeforeCounter returns a count of PrefixerMock.Prefix invocations
func (mmPrefix *PrefixerMock) PrefixBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPrefix.beforePrefixCounter)
}

// MinimockPrefixDone returns true if the count of the Prefix invocations corresponds
// the number of defined expectations
func (m *PrefixerMock) MinimockPrefixDone() bool {
	if m.PrefixMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.PrefixMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.PrefixMock.invocationsDone()
}

// MinimockPrefixInspect logs each unmet expectation
func (m *PrefixerMock) MinimockPrefixInspect() {
	for _, e := range m.PrefixMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to PrefixerMock.Prefix")
		}
	}

	afterPrefixCounter := mm_atomic.LoadUint64(&m.afterPrefixCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.PrefixMock.defaultExpectation != nil && afterPrefixCounter < 1 {
		m.t.Errorf("Expected call to PrefixerMock.Prefix at\n%s", m.PrefixMock.defaultExpectation.returnOrigin)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcPrefix != nil && afterPrefixCounter < 1 {
		m.t.Errorf("Expected call to PrefixerMock.Prefix at\n%s", m.funcPrefixOrigin)
	}

	if !m.PrefixMock.invocationsDone() && afterPrefixCounter > 0 {
		m.t.Errorf("Expected %d calls to PrefixerMock.Prefix at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.PrefixMock.expectedInvocations), m.PrefixMock.expectedInvocationsOrigin, afterPrefixCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *PrefixerMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockPrefixInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *PrefixerMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *PrefixerMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockPrefixDone()
}
