// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package storage

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/tarantool/go-storage/v2/kv"
	"github.com/tarantool/go-storage/v2/locker"
	txPkg "github.com/tarantool/go-storage/v2/tx"
	"github.com/tarantool/go-storage/v2/watch"
)

// StorageMock implements Storage
type StorageMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcLockerFactory          func() (f1 locker.Factory)
	funcLockerFactoryOrigin    string
	inspectFuncLockerFactory   func()
	afterLockerFactoryCounter  uint64
	beforeLockerFactoryCounter uint64
	LockerFactoryMock          mStorageMockLockerFactory

	funcNewLocker          func(ctx context.Context, name string, opts ...locker.Option) (l1 locker.Locker, err error)
	funcNewLockerOrigin    string
	inspectFuncNewLocker   func(ctx context.Context, name string, opts ...locker.Option)
	afterNewLockerCounter  uint64
	beforeNewLockerCounter uint64
	NewLockerMock          mStorageMockNewLocker

	funcRange          func(ctx context.Context, opts ...RangeOption) (ka1 []kv.KeyValue, err error)
	funcRangeOrigin    string
	inspectFuncRange   func(ctx context.Context, opts ...RangeOption)
	afterRangeCounter  uint64
	beforeRangeCounter uint64
	RangeMock          mStorageMockRange

	funcTx          func(ctx context.Context) (t1 txPkg.Tx)
	funcTxOrigin    string
	inspectFuncTx   func(ctx context.Context)
	afterTxCounter  uint64
	beforeTxCounter uint64
	TxMock          mStorageMockTx

	funcTxFactory          func() (f1 txPkg.Factory)
	funcTxFactoryOrigin    string
	inspectFuncTxFactory   func()
	afterTxFactoryCounter  uint64
	beforeTxFactoryCounter uint64
	TxFactoryMock          mStorageMockTxFactory

	funcWatch          func(ctx context.Context, key []byte) (ch1 <-chan watch.Event)
	funcWatchOrigin    string
	inspectFuncWatch   func(ctx context.Context, key []byte)
	afterWatchCounter  uint64
	beforeWatchCounter uint64
	WatchMock          mStorageMockWatch
}

// NewStorageMock returns a mock for Storage
func NewStorageMock(t minimock.Tester) *StorageMock {
	m := &StorageMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.LockerFactoryMock = mStorageMockLockerFactory{mock: m}

	m.NewLockerMock = mStorageMockNewLocker{mock: m}
	m.NewLockerMock.callArgs = []*StorageMockNewLockerParams{}

	m.RangeMock = mStorageMockRange{mock: m}
	m.RangeMock.callArgs = []*StorageMockRangeParams{}

	m.TxMock = mStorageMockTx{mock: m}
	m.TxMock.callArgs = []*StorageMockTxParams{}

	m.TxFactoryMock = mStorageMockTxFactory{mock: m}

	m.WatchMock = mStorageMockWatch{mock: m}
	m.WatchMock.callArgs = []*StorageMockWatchParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mStorageMockLockerFactory struct {
	optional           bool
	mock               *StorageMock
	defaultExpectation *StorageMockLockerFactoryExpectation
	expectations       []*StorageMockLockerFactoryExpectation

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StorageMockLockerFactoryExpectation specifies expectation struct of the Storage.LockerFactory
type StorageMockLockerFactoryExpectation struct {
	mock *StorageMock

	results      *StorageMockLockerFactoryResults
	returnOrigin string
	Counter      uint64
}

// StorageMockLockerFactoryResults contains results of the Storage.LockerFactory
type StorageMockLockerFactoryResults struct {
	f1 locker.Factory
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmLockerFactory *mStorageMockLockerFactory) Optional() *mStorageMockLockerFactory {
	mmLockerFactory.optional = true
	return mmLockerFactory
}

// Expect sets up expected params for Storage.LockerFactory
func (mmLockerFactory *mStorageMockLockerFactory) Expect() *mStorageMockLockerFactory {
	if mmLockerFactory.mock.funcLockerFactory != nil {
		mmLockerFactory.mock.t.Fatalf("StorageMock.LockerFactory mock is already set by Set")
	}

	if mmLockerFactory.defaultExpectation == nil {
		mmLockerFactory.defaultExpectation = &StorageMockLockerFactoryExpectation{}
	}

	return mmLockerFactory
}

// Inspect accepts an inspector function that has same arguments as the Storage.LockerFactory
func (mmLockerFactory *mStorageMockLockerFactory) Inspect(f func()) *mStorageMockLockerFactory {
	if mmLockerFactory.mock.inspectFuncLockerFactory != nil {
		mmLockerFactory.mock.t.Fatalf("Inspect function is already set for StorageMock.LockerFactory")
	}

	mmLockerFactory.mock.inspectFuncLockerFactory = f

	return mmLockerFactory
}

// Return sets up results that will be returned by Storage.LockerFactory
func (mmLockerFactory *mStorageMockLockerFactory) Return(f1 locker.Factory) *StorageMock {
	if mmLockerFactory.mock.funcLockerFactory != nil {
		mmLockerFactory.mock.t.Fatalf("StorageMock.LockerFactory mock is already set by Set")
	}

	if mmLockerFactory.defaultExpectation == nil {
		mmLockerFactory.defaultExpectation = &StorageMockLockerFactoryExpectation{mock: mmLockerFactory.mock}
	}
	mmLockerFactory.defaultExpectation.results = &StorageMockLockerFactoryResults{f1}
	mmLockerFactory.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmLockerFactory.mock
}

// Set uses given function f to mock the Storage.LockerFactory method
func (mmLockerFactory *mStorageMockLockerFactory) Set(f func() (f1 locker.Factory)) *StorageMock {
	if mmLockerFactory.defaultExpectation != nil {
		mmLockerFactory.mock.t.Fatalf("Default expectation is already set for the Storage.LockerFactory method")
	}

	if len(mmLockerFactory.expectations) > 0 {
		mmLockerFactory.mock.t.Fatalf("Some expectations are already set for the Storage.LockerFactory method")
	}

	mmLockerFactory.mock.funcLockerFactory = f
	mmLockerFactory.mock.funcLockerFactoryOrigin = minimock.CallerInfo(1)
	return mmLockerFactory.mock
}

// Times sets number of times Storage.LockerFactory should be invoked
func (mmLockerFactory *mStorageMockLockerFactory) Times(n uint64) *mStorageMockLockerFactory {
	if n == 0 {
		mmLockerFactory.mock.t.Fatalf("Times of StorageMock.LockerFactory mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmLockerFactory.expectedInvocations, n)
	mmLockerFactory.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmLockerFactory
}

func (mmLockerFactory *mStorageMockLockerFactory) invocationsDone() bool {
	if len(mmLockerFactory.expectations) == 0 && mmLockerFactory.defaultExpectation == nil && mmLockerFactory.mock.funcLockerFactory == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmLockerFactory.mock.afterLockerFactoryCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmLockerFactory.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// LockerFactory implements Storage
func (mmLockerFactory *StorageMock) LockerFactory() (f1 locker.Factory) {
	mm_atomic.AddUint64(&mmLockerFactory.beforeLockerFactoryCounter, 1)
	defer mm_atomic.AddUint64(&mmLockerFactory.afterLockerFactoryCounter, 1)

	mmLockerFactory.t.Helper()

	if mmLockerFactory.inspectFuncLockerFactory != nil {
		mmLockerFactory.inspectFuncLockerFactory()
	}

	if mmLockerFactory.LockerFactoryMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmLockerFactory.LockerFactoryMock.defaultExpectation.Counter, 1)

		mm_results := mmLockerFactory.LockerFactoryMock.defaultExpectation.results
		if mm_results == nil {
			mmLockerFactory.t.Fatal("No results are set for the StorageMock.LockerFactory")
		}
		return (*mm_results).f1
	}
	if mmLockerFactory.funcLockerFactory != nil {
		return mmLockerFactory.funcLockerFactory()
	}
	mmLockerFactory.t.Fatalf("Unexpected call to StorageMock.LockerFactory.")
	return
}

// LockerFactoryAfterCounter returns a count of finished StorageMock.LockerFactory invocations
func (mmLockerFactory *StorageMock) LockerFactoryAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmLockerFactory.afterLockerFactoryCounter)
}

// LockerFactoryBeforeCounter returns a count of StorageMock.LockerFactory invocations
func (mmLockerFactory *StorageMock) LockerFactoryBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmLockerFactory.beforeLockerFactoryCounter)
}

// MinimockLockerFactoryDone returns true if the count of the LockerFactory invocations corresponds
// the number of defined expectations
func (m *StorageMock) MinimockLockerFactoryDone() bool {
	if m.LockerFactoryMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.LockerFactoryMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.LockerFactoryMock.invocationsDone()
}

// MinimockLockerFactoryInspect logs each unmet expectation
func (m *StorageMock) MinimockLockerFactoryInspect() {
	for _, e := range m.LockerFactoryMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to StorageMock.LockerFactory")
		}
	}

	afterLockerFactoryCounter := mm_atomic.LoadUint64(&m.afterLockerFactoryCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.LockerFactoryMock.defaultExpectation != nil && afterLockerFactoryCounter < 1 {
		m.t.Errorf("Expected call to StorageMock.LockerFactory at\n%s", m.LockerFactoryMock.defaultExpectation.returnOrigin)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcLockerFactory != nil && afterLockerFactoryCounter < 1 {
		m.t.Errorf("Expected call to StorageMock.LockerFactory at\n%s", m.funcLockerFactoryOrigin)
	}

	if !m.LockerFactoryMock.invocationsDone() && afterLockerFactoryCounter > 0 {
		m.t.Errorf("Expected %d calls to StorageMock.LockerFactory at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.LockerFactoryMock.expectedInvocations), m.LockerFactoryMock.expectedInvocationsOrigin, afterLockerFactoryCounter)
	}
}

type mStorageMockNewLocker struct {
	optional           bool
	mock               *StorageMock
	defaultExpectation *StorageMockNewLockerExpectation
	expectations       []*StorageMockNewLockerExpectation

	callArgs []*StorageMockNewLockerParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StorageMockNewLockerExpectation specifies expectation struct of the Storage.NewLocker
type StorageMockNewLockerExpectation struct {
	mock               *StorageMock
	params             *StorageMockNewLockerParams
	paramPtrs          *StorageMockNewLockerParamPtrs
	expectationOrigins StorageMockNewLockerExpectationOrigins
	results            *StorageMockNewLockerResults
	returnOrigin       string
	Counter            uint64
}

// StorageMockNewLockerParams contains parameters of the Storage.NewLocker
type StorageMockNewLockerParams struct {
	ctx  context.Context
	name string
	opts []locker.Option
}

// StorageMockNewLockerParamPtrs contains pointers to parameters of the Storage.NewLocker
type StorageMockNewLockerParamPtrs struct {
	ctx  *context.Context
	name *string
	opts *[]locker.Option
}

// StorageMockNewLockerResults contains results of the Storage.NewLocker
type StorageMockNewLockerResults struct {
	l1  locker.Locker
	err error
}

// StorageMockNewLockerOrigins contains origins of expectations of the Storage.NewLocker
type StorageMockNewLockerExpectationOrigins struct {
	origin     string
	originCtx  string
	originName string
	originOpts string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmNewLocker *mStorageMockNewLocker) Optional() *mStorageMockNewLocker {
	mmNewLocker.optional = true
	return mmNewLocker
}

// Expect sets up expected params for Storage.NewLocker
func (mmNewLocker *mStorageMockNewLocker) Expect(ctx context.Context, name string, opts ...locker.Option) *mStorageMockNewLocker {
	if mmNewLocker.mock.funcNewLocker != nil {
		mmNewLocker.mock.t.Fatalf("StorageMock.NewLocker mock is already set by Set")
	}

	if mmNewLocker.defaultExpectation == nil {
		mmNewLocker.defaultExpectation = &StorageMockNewLockerExpectation{}
	}

	if mmNewLocker.defaultExpectation.paramPtrs != nil {
		mmNewLocker.mock.t.Fatalf("StorageMock.NewLocker mock is already set by ExpectParams functions")
	}

	mmNewLocker.defaultExpectation.params = &StorageMockNewLockerParams{ctx, name, opts}
	mmNewLocker.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmNewLocker.expectations {
		if minimock.Equal(e.params, mmNewLocker.defaultExpectation.params) {
			mmNewLocker.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmNewLocker.defaultExpectation.params)
		}
	}

	return mmNewLocker
}

// ExpectCtxParam1 sets up expected param ctx for Storage.NewLocker
func (mmNewLocker *mStorageMockNewLocker) ExpectCtxParam1(ctx context.Context) *mStorageMockNewLocker {
	if mmNewLocker.mock.funcNewLocker != nil {
		mmNewLocker.mock.t.Fatalf("StorageMock.NewLocker mock is already set by Set")
	}

	if mmNewLocker.defaultExpectation == nil {
		mmNewLocker.defaultExpectation = &StorageMockNewLockerExpectation{}
	}

	if mmNewLocker.defaultExpectation.params != nil {
		mmNewLocker.mock.t.Fatalf("StorageMock.NewLocker mock is already set by Expect")
	}

	if mmNewLocker.defaultExpectation.paramPtrs == nil {
		mmNewLocker.defaultExpectation.paramPtrs = &StorageMockNewLockerParamPtrs{}
	}
	mmNewLocker.defaultExpectation.paramPtrs.ctx = &ctx
	mmNewLocker.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmNewLocker
}

// ExpectNameParam2 sets up expected param name for Storage.NewLocker
func (mmNewLocker *mStorageMockNewLocker) ExpectNameParam2(name string) *mStorageMockNewLocker {
	if mmNewLocker.mock.funcNewLocker != nil {
		mmNewLocker.mock.t.Fatalf("StorageMock.NewLocker mock is already set by Set")
	}

	if mmNewLocker.defaultExpectation == nil {
		mmNewLocker.defaultExpectation = &StorageMockNewLockerExpectation{}
	}

	if mmNewLocker.defaultExpectation.params != nil {
		mmNewLocker.mock.t.Fatalf("StorageMock.NewLocker mock is already set by Expect")
	}

	if mmNewLocker.defaultExpectation.paramPtrs == nil {
		mmNewLocker.defaultExpectation.paramPtrs = &StorageMockNewLockerParamPtrs{}
	}
	mmNewLocker.defaultExpectation.paramPtrs.name = &name
	mmNewLocker.defaultExpectation.expectationOrigins.originName = minimock.CallerInfo(1)

	return mmNewLocker
}

// ExpectOptsParam3 sets up expected param opts for Storage.NewLocker
func (mmNewLocker *mStorageMockNewLocker) ExpectOptsParam3(opts ...locker.Option) *mStorageMockNewLocker {
	if mmNewLocker.mock.funcNewLocker != nil {
		mmNewLocker.mock.t.Fatalf("StorageMock.NewLocker mock is already set by Set")
	}

	if mmNewLocker.defaultExpectation == nil {
		mmNewLocker.defaultExpectation = &StorageMockNewLockerExpectation{}
	}

	if mmNewLocker.defaultExpectation.params != nil {
		mmNewLocker.mock.t.Fatalf("StorageMock.NewLocker mock is already set by Expect")
	}

	if mmNewLocker.defaultExpectation.paramPtrs == nil {
		mmNewLocker.defaultExpectation.paramPtrs = &StorageMockNewLockerParamPtrs{}
	}
	mmNewLocker.defaultExpectation.paramPtrs.opts = &opts
	mmNewLocker.defaultExpectation.expectationOrigins.originOpts = minimock.CallerInfo(1)

	return mmNewLocker
}

// Inspect accepts an inspector function that has same arguments as the Storage.NewLocker
func (mmNewLocker *mStorageMockNewLocker) Inspect(f func(ctx context.Context, name string, opts ...locker.Option)) *mStorageMockNewLocker {
	if mmNewLocker.mock.inspectFuncNewLocker != nil {
		mmNewLocker.mock.t.Fatalf("Inspect function is already set for StorageMock.NewLocker")
	}

	mmNewLocker.mock.inspectFuncNewLocker = f

	return mmNewLocker
}

// Return sets up results that will be returned by Storage.NewLocker
func (mmNewLocker *mStorageMockNewLocker) Return(l1 locker.Locker, err error) *StorageMock {
	if mmNewLocker.mock.funcNewLocker != nil {
		mmNewLocker.mock.t.Fatalf("StorageMock.NewLocker mock is already set by Set")
	}

	if mmNewLocker.defaultExpectation == nil {
		mmNewLocker.defaultExpectation = &StorageMockNewLockerExpectation{mock: mmNewLocker.mock}
	}
	mmNewLocker.defaultExpectation.results = &StorageMockNewLockerResults{l1, err}
	mmNewLocker.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmNewLocker.mock
}

// Set uses given function f to mock the Storage.NewLocker method
func (mmNewLocker *mStorageMockNewLocker) Set(f func(ctx context.Context, name string, opts ...locker.Option) (l1 locker.Locker, err error)) *StorageMock {
	if mmNewLocker.defaultExpectation != nil {
		mmNewLocker.mock.t.Fatalf("Default expectation is already set for the Storage.NewLocker method")
	}

	if len(mmNewLocker.expectations) > 0 {
		mmNewLocker.mock.t.Fatalf("Some expectations are already set for the Storage.NewLocker method")
	}

	mmNewLocker.mock.funcNewLocker = f
	mmNewLocker.mock.funcNewLockerOrigin = minimock.CallerInfo(1)
	return mmNewLocker.mock
}

// When sets expectation for the Storage.NewLocker which will trigger the result defined by the following
// Then helper
func (mmNewLocker *mStorageMockNewLocker) When(ctx context.Context, name string, opts ...locker.Option) *StorageMockNewLockerExpectation {
	if mmNewLocker.mock.funcNewLocker != nil {
		mmNewLocker.mock.t.Fatalf("StorageMock.NewLocker mock is already set by Set")
	}

	expectation := &StorageMockNewLockerExpectation{
		mock:               mmNewLocker.mock,
		params:             &StorageMockNewLockerParams{ctx, name, opts},
		expectationOrigins: StorageMockNewLockerExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmNewLocker.expectations = append(mmNewLocker.expectations, expectation)
	return expectation
}

// Then sets up Storage.NewLocker return parameters for the expectation previously defined by the When method
func (e *StorageMockNewLockerExpectation) Then(l1 locker.Locker, err error) *StorageMock {
	e.results = &StorageMockNewLockerResults{l1, err}
	return e.mock
}

// Times sets number of times Storage.NewLocker should be invoked
func (mmNewLocker *mStorageMockNewLocker) Times(n uint64) *mStorageMockNewLocker {
	if n == 0 {
		mmNewLocker.mock.t.Fatalf("Times of StorageMock.NewLocker mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmNewLocker.expectedInvocations, n)
	mmNewLocker.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmNewLocker
}

func (mmNewLocker *mStorageMockNewLocker) invocationsDone() bool {
	if len(mmNewLocker.expectations) == 0 && mmNewLocker.defaultExpectation == nil && mmNewLocker.mock.funcNewLocker == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmNewLocker.mock.afterNewLockerCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmNewLocker.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// NewLocker implements Storage
func (mmNewLocker *StorageMock) NewLocker(ctx context.Context, name string, opts ...locker.Option) (l1 locker.Locker, err error) {
	mm_atomic.AddUint64(&mmNewLocker.beforeNewLockerCounter, 1)
	defer mm_atomic.AddUint64(&mmNewLocker.afterNewLockerCounter, 1)

	mmNewLocker.t.Helper()

	if mmNewLocker.inspectFuncNewLocker != nil {
		mmNewLocker.inspectFuncNewLocker(ctx, name, opts...)
	}

	mm_params := StorageMockNewLockerParams{ctx, name, opts}

	// Record call args
	mmNewLocker.NewLockerMock.mutex.Lock()
	mmNewLocker.NewLockerMock.callArgs = append(mmNewLocker.NewLockerMock.callArgs, &mm_params)
	mmNewLocker.NewLockerMock.mutex.Unlock()

	for _, e := range mmNewLocker.NewLockerMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.l1, e.results.err
		}
	}

	if mmNewLocker.NewLockerMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmNewLocker.NewLockerMock.defaultExpectation.Counter, 1)
		mm_want := mmNewLocker.NewLockerMock.defaultExpectation.params
		mm_want_ptrs := mmNewLocker.NewLockerMock.defaultExpectation.paramPtrs

		mm_got := StorageMockNewLockerParams{ctx, name, opts}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmNewLocker.t.Errorf("StorageMock.NewLocker got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmNewLocker.NewLockerMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.name != nil && !minimock.Equal(*mm_want_ptrs.name, mm_got.name) {
				mmNewLocker.t.Errorf("StorageMock.NewLocker got unexpected parameter name, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmNewLocker.NewLockerMock.defaultExpectation.expectationOrigins.originName, *mm_want_ptrs.name, mm_got.name, minimock.Diff(*mm_want_ptrs.name, mm_got.name))
			}

			if mm_want_ptrs.opts != nil && !minimock.Equal(*mm_want_ptrs.opts, mm_got.opts) {
				mmNewLocker.t.Errorf("StorageMock.NewLocker got unexpected parameter opts, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmNewLocker.NewLockerMock.defaultExpectation.expectationOrigins.originOpts, *mm_want_ptrs.opts, mm_got.opts, minimock.Diff(*mm_want_ptrs.opts, mm_got.opts))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmNewLocker.t.Errorf("StorageMock.NewLocker got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmNewLocker.NewLockerMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmNewLocker.NewLockerMock.defaultExpectation.results
		if mm_results == nil {
			mmNewLocker.t.Fatal("No results are set for the StorageMock.NewLocker")
		}
		return (*mm_results).l1, (*mm_results).err
	}
	if mmNewLocker.funcNewLocker != nil {
		return mmNewLocker.funcNewLocker(ctx, name, opts...)
	}
	mmNewLocker.t.Fatalf("Unexpected call to StorageMock.NewLocker. %v %v %v", ctx, name, opts)
	return
}

// NewLockerAfterCounter returns a count of finished StorageMock.NewLocker invocations
func (mmNewLocker *StorageMock) NewLockerAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmNewLocker.afterNewLockerCounter)
}

// NewLockerBeforeCounter returns a count of StorageMock.NewLocker invocations
func (mmNewLocker *StorageMock) NewLockerBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmNewLocker.beforeNewLockerCounter)
}

// Calls returns a list of arguments used in each call to StorageMock.NewLocker.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmNewLocker *mStorageMockNewLocker) Calls() []*StorageMockNewLockerParams {
	mmNewLocker.mutex.RLock()

	argCopy := make([]*StorageMockNewLockerParams, len(mmNewLocker.callArgs))
	copy(argCopy, mmNewLocker.callArgs)

	mmNewLocker.mutex.RUnlock()

	return argCopy
}

// MinimockNewLockerDone returns true if the count of the NewLocker invocations corresponds
// the number of defined expectations
func (m *StorageMock) MinimockNewLockerDone() bool {
	if m.NewLockerMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.NewLockerMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.NewLockerMock.invocationsDone()
}

// MinimockNewLockerInspect logs each unmet expectation
func (m *StorageMock) MinimockNewLockerInspect() {
	for _, e := range m.NewLockerMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StorageMock.NewLocker at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterNewLockerCounter := mm_atomic.LoadUint64(&m.afterNewLockerCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.NewLockerMock.defaultExpectation != nil && afterNewLockerCounter < 1 {
		if m.NewLockerMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StorageMock.NewLocker at\n%s", m.NewLockerMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StorageMock.NewLocker at\n%s with params: %#v", m.NewLockerMock.defaultExpectation.expectationOrigins.origin, *m.NewLockerMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcNewLocker != nil && afterNewLockerCounter < 1 {
		m.t.Errorf("Expected call to StorageMock.NewLocker at\n%s", m.funcNewLockerOrigin)
	}

	if !m.NewLockerMock.invocationsDone() && afterNewLockerCounter > 0 {
		m.t.Errorf("Expected %d calls to StorageMock.NewLocker at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.NewLockerMock.expectedInvocations), m.NewLockerMock.expectedInvocationsOrigin, afterNewLockerCounter)
	}
}

type mStorageMockRange struct {
	optional           bool
	mock               *StorageMock
	defaultExpectation *StorageMockRangeExpectation
	expectations       []*StorageMockRangeExpectation

	callArgs []*StorageMockRangeParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StorageMockRangeExpectation specifies expectation struct of the Storage.Range
type StorageMockRangeExpectation struct {
	mock               *StorageMock
	params             *StorageMockRangeParams
	paramPtrs          *StorageMockRangeParamPtrs
	expectationOrigins StorageMockRangeExpectationOrigins
	results            *StorageMockRangeResults
	returnOrigin       string
	Counter            uint64
}

// StorageMockRangeParams contains parameters of the Storage.Range
type StorageMockRangeParams struct {
	ctx  context.Context
	opts []RangeOption
}

// StorageMockRangeParamPtrs contains pointers to parameters of the Storage.Range
type StorageMockRangeParamPtrs struct {
	ctx  *context.Context
	opts *[]RangeOption
}

// StorageMockRangeResults contains results of the Storage.Range
type StorageMockRangeResults struct {
	ka1 []kv.KeyValue
	err error
}

// StorageMockRangeOrigins contains origins of expectations of the Storage.Range
type StorageMockRangeExpectationOrigins struct {
	origin     string
	originCtx  string
	originOpts string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmRange *mStorageMockRange) Optional() *mStorageMockRange {
	mmRange.optional = true
	return mmRange
}

// Expect sets up expected params for Storage.Range
func (mmRange *mStorageMockRange) Expect(ctx context.Context, opts ...RangeOption) *mStorageMockRange {
	if mmRange.mock.funcRange != nil {
		mmRange.mock.t.Fatalf("StorageMock.Range mock is already set by Set")
	}

	if mmRange.defaultExpectation == nil {
		mmRange.defaultExpectation = &StorageMockRangeExpectation{}
	}

	if mmRange.defaultExpectation.paramPtrs != nil {
		mmRange.mock.t.Fatalf("StorageMock.Range mock is already set by ExpectParams functions")
	}

	mmRange.defaultExpectation.params = &StorageMockRangeParams{ctx, opts}
	mmRange.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmRange.expectations {
		if minimock.Equal(e.params, mmRange.defaultExpectation.params) {
			mmRange.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmRange.defaultExpectation.params)
		}
	}

	return mmRange
}

// ExpectCtxParam1 sets up expected param ctx for Storage.Range
func (mmRange *mStorageMockRange) ExpectCtxParam1(ctx context.Context) *mStorageMockRange {
	if mmRange.mock.funcRange != nil {
		mmRange.mock.t.Fatalf("StorageMock.Range mock is already set by Set")
	}

	if mmRange.defaultExpectation == nil {
		mmRange.defaultExpectation = &StorageMockRangeExpectation{}
	}

	if mmRange.defaultExpectation.params != nil {
		mmRange.mock.t.Fatalf("StorageMock.Range mock is already set by Expect")
	}

	if mmRange.defaultExpectation.paramPtrs == nil {
		mmRange.defaultExpectation.paramPtrs = &StorageMockRangeParamPtrs{}
	}
	mmRange.defaultExpectation.paramPtrs.ctx = &ctx
	mmRange.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmRange
}

// ExpectOptsParam2 sets up expected param opts for Storage.Range
func (mmRange *mStorageMockRange) ExpectOptsParam2(opts ...RangeOption) *mStorageMockRange {
	if mmRange.mock.funcRange != nil {
		mmRange.mock.t.Fatalf("StorageMock.Range mock is already set by Set")
	}

	if mmRange.defaultExpectation == nil {
		mmRange.defaultExpectation = &StorageMockRangeExpectation{}
	}

	if mmRange.defaultExpectation.params != nil {
		mmRange.mock.t.Fatalf("StorageMock.Range mock is already set by Expect")
	}

	if mmRange.defaultExpectation.paramPtrs == nil {
		mmRange.defaultExpectation.paramPtrs = &StorageMockRangeParamPtrs{}
	}
	mmRange.defaultExpectation.paramPtrs.opts = &opts
	mmRange.defaultExpectation.expectationOrigins.originOpts = minimock.CallerInfo(1)

	return mmRange
}

// Inspect accepts an inspector function that has same arguments as the Storage.Range
func (mmRange *mStorageMockRange) Inspect(f func(ctx context.Context, opts ...RangeOption)) *mStorageMockRange {
	if mmRange.mock.inspectFuncRange != nil {
		mmRange.mock.t.Fatalf("Inspect function is already set for StorageMock.Range")
	}

	mmRange.mock.inspectFuncRange = f

	return mmRange
}

// Return sets up results that will be returned by Storage.Range
func (mmRange *mStorageMockRange) Return(ka1 []kv.KeyValue, err error) *StorageMock {
	if mmRange.mock.funcRange != nil {
		mmRange.mock.t.Fatalf("StorageMock.Range mock is already set by Set")
	}

	if mmRange.defaultExpectation == nil {
		mmRange.defaultExpectation = &StorageMockRangeExpectation{mock: mmRange.mock}
	}
	mmRange.defaultExpectation.results = &StorageMockRangeResults{ka1, err}
	mmRange.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmRange.mock
}

// Set uses given function f to mock the Storage.Range method
func (mmRange *mStorageMockRange) Set(f func(ctx context.Context, opts ...RangeOption) (ka1 []kv.KeyValue, err error)) *StorageMock {
	if mmRange.defaultExpectation != nil {
		mmRange.mock.t.Fatalf("Default expectation is already set for the Storage.Range method")
	}

	if len(mmRange.expectations) > 0 {
		mmRange.mock.t.Fatalf("Some expectations are already set for the Storage.Range method")
	}

	mmRange.mock.funcRange = f
	mmRange.mock.funcRangeOrigin = minimock.CallerInfo(1)
	return mmRange.mock
}

// When sets expectation for the Storage.Range which will trigger the result defined by the following
// Then helper
func (mmRange *mStorageMockRange) When(ctx context.Context, opts ...RangeOption) *StorageMockRangeExpectation {
	if mmRange.mock.funcRange != nil {
		mmRange.mock.t.Fatalf("StorageMock.Range mock is already set by Set")
	}

	expectation := &StorageMockRangeExpectation{
		mock:               mmRange.mock,
		params:             &StorageMockRangeParams{ctx, opts},
		expectationOrigins: StorageMockRangeExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmRange.expectations = append(mmRange.expectations, expectation)
	return expectation
}

// Then sets up Storage.Range return parameters for the expectation previously defined by the When method
func (e *StorageMockRangeExpectation) Then(ka1 []kv.KeyValue, err error) *StorageMock {
	e.results = &StorageMockRangeResults{ka1, err}
	return e.mock
}

// Times sets number of times Storage.Range should be invoked
func (mmRange *mStorageMockRange) Times(n uint64) *mStorageMockRange {
	if n == 0 {
		mmRange.mock.t.Fatalf("Times of StorageMock.Range mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmRange.expectedInvocations, n)
	mmRange.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmRange
}

func (mmRange *mStorageMockRange) invocationsDone() bool {
	if len(mmRange.expectations) == 0 && mmRange.defaultExpectation == nil && mmRange.mock.funcRange == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmRange.mock.afterRangeCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmRange.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Range implements Storage
func (mmRange *StorageMock) Range(ctx context.Context, opts ...RangeOption) (ka1 []kv.KeyValue, err error) {
	mm_atomic.AddUint64(&mmRange.beforeRangeCounter, 1)
	defer mm_atomic.AddUint64(&mmRange.afterRangeCounter, 1)

	mmRange.t.Helper()

	if mmRange.inspectFuncRange != nil {
		mmRange.inspectFuncRange(ctx, opts...)
	}

	mm_params := StorageMockRangeParams{ctx, opts}

	// Record call args
	mmRange.RangeMock.mutex.Lock()
	mmRange.RangeMock.callArgs = append(mmRange.RangeMock.callArgs, &mm_params)
	mmRange.RangeMock.mutex.Unlock()

	for _, e := range mmRange.RangeMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ka1, e.results.err
		}
	}

	if mmRange.RangeMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmRange.RangeMock.defaultExpectation.Counter, 1)
		mm_want := mmRange.RangeMock.defaultExpectation.params
		mm_want_ptrs := mmRange.RangeMock.defaultExpectation.paramPtrs

		mm_got := StorageMockRangeParams{ctx, opts}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmRange.t.Errorf("StorageMock.Range got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRange.RangeMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.opts != nil && !minimock.Equal(*mm_want_ptrs.opts, mm_got.opts) {
				mmRange.t.Errorf("StorageMock.Range got unexpected parameter opts, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRange.RangeMock.defaultExpectation.expectationOrigins.originOpts, *mm_want_ptrs.opts, mm_got.opts, minimock.Diff(*mm_want_ptrs.opts, mm_got.opts))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmRange.t.Errorf("StorageMock.Range got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmRange.RangeMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmRange.RangeMock.defaultExpectation.results
		if mm_results == nil {
			mmRange.t.Fatal("No results are set for the StorageMock.Range")
		}
		return (*mm_results).ka1, (*mm_results).err
	}
	if mmRange.funcRange != nil {
		return mmRange.funcRange(ctx, opts...)
	}
	mmRange.t.Fatalf("Unexpected call to StorageMock.Range. %v %v", ctx, opts)
	return
}

// RangeAfterCounter returns a count of finished StorageMock.Range invocations
func (mmRange *StorageMock) RangeAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRange.afterRangeCounter)
}

// RangeBeforeCounter returns a count of StorageMock.Range invocations
func (mmRange *StorageMock) RangeBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRange.beforeRangeCounter)
}

// Calls returns a list of arguments used in each call to StorageMock.Range.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmRange *mStorageMockRange) Calls() []*StorageMockRangeParams {
	mmRange.mutex.RLock()

	argCopy := make([]*StorageMockRangeParams, len(mmRange.callArgs))
	copy(argCopy, mmRange.callArgs)

	mmRange.mutex.RUnlock()

	return argCopy
}

// MinimockRangeDone returns true if the count of the Range invocations corresponds
// the number of defined expectations
func (m *StorageMock) MinimockRangeDone() bool {
	if m.RangeMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.RangeMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.RangeMock.invocationsDone()
}

// MinimockRangeInspect logs each unmet expectation
func (m *StorageMock) MinimockRangeInspect() {
	for _, e := range m.RangeMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StorageMock.Range at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterRangeCounter := mm_atomic.LoadUint64(&m.afterRangeCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.RangeMock.defaultExpectation != nil && afterRangeCounter < 1 {
		if m.RangeMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StorageMock.Range at\n%s", m.RangeMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StorageMock.Range at\n%s with params: %#v", m.RangeMock.defaultExpectation.expectationOrigins.origin, *m.RangeMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRange != nil && afterRangeCounter < 1 {
		m.t.Errorf("Expected call to StorageMock.Range at\n%s", m.funcRangeOrigin)
	}

	if !m.RangeMock.invocationsDone() && afterRangeCounter > 0 {
		m.t.Errorf("Expected %d calls to StorageMock.Range at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.RangeMock.expectedInvocations), m.RangeMock.expectedInvocationsOrigin, afterRangeCounter)
	}
}

type mStorageMockTx struct {
	optional           bool
	mock               *StorageMock
	defaultExpectation *StorageMockTxExpectation
	expectations       []*StorageMockTxExpectation

	callArgs []*StorageMockTxParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StorageMockTxExpectation specifies expectation struct of the Storage.Tx
type StorageMockTxExpectation struct {
	mock               *StorageMock
	params             *StorageMockTxParams
	paramPtrs          *StorageMockTxParamPtrs
	expectationOrigins StorageMockTxExpectationOrigins
	results            *StorageMockTxResults
	returnOrigin       string
	Counter            uint64
}

// StorageMockTxParams contains parameters of the Storage.Tx
type StorageMockTxParams struct {
	ctx context.Context
}

// StorageMockTxParamPtrs contains pointers to parameters of the Storage.Tx
type StorageMockTxParamPtrs struct {
	ctx *context.Context
}

// StorageMockTxResults contains results of the Storage.Tx
type StorageMockTxResults struct {
	t1 txPkg.Tx
}

// StorageMockTxOrigins contains origins of expectations of the Storage.Tx
type StorageMockTxExpectationOrigins struct {
	origin    string
	originCtx string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmTx *mStorageMockTx) Optional() *mStorageMockTx {
	mmTx.optional = true
	return mmTx
}

// Expect sets up expected params for Storage.Tx
func (mmTx *mStorageMockTx) Expect(ctx context.Context) *mStorageMockTx {
	if mmTx.mock.funcTx != nil {
		mmTx.mock.t.Fatalf("StorageMock.Tx mock is already set by Set")
	}

	if mmTx.defaultExpectation == nil {
		mmTx.defaultExpectation = &StorageMockTxExpectation{}
	}

	if mmTx.defaultExpectation.paramPtrs != nil {
		mmTx.mock.t.Fatalf("StorageMock.Tx mock is already set by ExpectParams functions")
	}

	mmTx.defaultExpectation.params = &StorageMockTxParams{ctx}
	mmTx.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmTx.expectations {
		if minimock.Equal(e.params, mmTx.defaultExpectation.params) {
			mmTx.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmTx.defaultExpectation.params)
		}
	}

	return mmTx
}

// ExpectCtxParam1 sets up expected param ctx for Storage.Tx
func (mmTx *mStorageMockTx) ExpectCtxParam1(ctx context.Context) *mStorageMockTx {
	if mmTx.mock.funcTx != nil {
		mmTx.mock.t.Fatalf("StorageMock.Tx mock is already set by Set")
	}

	if mmTx.defaultExpectation == nil {
		mmTx.defaultExpectation = &StorageMockTxExpectation{}
	}

	if mmTx.defaultExpectation.params != nil {
		mmTx.mock.t.Fatalf("StorageMock.Tx mock is already set by Expect")
	}

	if mmTx.defaultExpectation.paramPtrs == nil {
		mmTx.defaultExpectation.paramPtrs = &StorageMockTxParamPtrs{}
	}
	mmTx.defaultExpectation.paramPtrs.ctx = &ctx
	mmTx.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmTx
}

// Inspect accepts an inspector function that has same arguments as the Storage.Tx
func (mmTx *mStorageMockTx) Inspect(f func(ctx context.Context)) *mStorageMockTx {
	if mmTx.mock.inspectFuncTx != nil {
		mmTx.mock.t.Fatalf("Inspect function is already set for StorageMock.Tx")
	}

	mmTx.mock.inspectFuncTx = f

	return mmTx
}

// Return sets up results that will be returned by Storage.Tx
func (mmTx *mStorageMockTx) Return(t1 txPkg.Tx) *StorageMock {
	if mmTx.mock.funcTx != nil {
		mmTx.mock.t.Fatalf("StorageMock.Tx mock is already set by Set")
	}

	if mmTx.defaultExpectation == nil {
		mmTx.defaultExpectation = &StorageMockTxExpectation{mock: mmTx.mock}
	}
	mmTx.defaultExpectation.results = &StorageMockTxResults{t1}
	mmTx.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmTx.mock
}

// Set uses given function f to mock the Storage.Tx method
func (mmTx *mStorageMockTx) Set(f func(ctx context.Context) (t1 txPkg.Tx)) *StorageMock {
	if mmTx.defaultExpectation != nil {
		mmTx.mock.t.Fatalf("Default expectation is already set for the Storage.Tx method")
	}

	if len(mmTx.expectations) > 0 {
		mmTx.mock.t.Fatalf("Some expectations are already set for the Storage.Tx method")
	}

	mmTx.mock.funcTx = f
	mmTx.mock.funcTxOrigin = minimock.CallerInfo(1)
	return mmTx.mock
}

// When sets expectation for the Storage.Tx which will trigger the result defined by the following
// Then helper
func (mmTx *mStorageMockTx) When(ctx context.Context) *StorageMockTxExpectation {
	if mmTx.mock.funcTx != nil {
		mmTx.mock.t.Fatalf("StorageMock.Tx mock is already set by Set")
	}

	expectation := &StorageMockTxExpectation{
		mock:               mmTx.mock,
		params:             &StorageMockTxParams{ctx},
		expectationOrigins: StorageMockTxExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmTx.expectations = append(mmTx.expectations, expectation)
	return expectation
}

// Then sets up Storage.Tx return parameters for the expectation previously defined by the When method
func (e *StorageMockTxExpectation) Then(t1 txPkg.Tx) *StorageMock {
	e.results = &StorageMockTxResults{t1}
	return e.mock
}

// Times sets number of times Storage.Tx should be invoked
func (mmTx *mStorageMockTx) Times(n uint64) *mStorageMockTx {
	if n == 0 {
		mmTx.mock.t.Fatalf("Times of StorageMock.Tx mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmTx.expectedInvocations, n)
	mmTx.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmTx
}

func (mmTx *mStorageMockTx) invocationsDone() bool {
	if len(mmTx.expectations) == 0 && mmTx.defaultExpectation == nil && mmTx.mock.funcTx == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmTx.mock.afterTxCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmTx.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Tx implements Storage
func (mmTx *StorageMock) Tx(ctx context.Context) (t1 txPkg.Tx) {
	mm_atomic.AddUint64(&mmTx.beforeTxCounter, 1)
	defer mm_atomic.AddUint64(&mmTx.afterTxCounter, 1)

	mmTx.t.Helper()

	if mmTx.inspectFuncTx != nil {
		mmTx.inspectFuncTx(ctx)
	}

	mm_params := StorageMockTxParams{ctx}

	// Record call args
	mmTx.TxMock.mutex.Lock()
	mmTx.TxMock.callArgs = append(mmTx.TxMock.callArgs, &mm_params)
	mmTx.TxMock.mutex.Unlock()

	for _, e := range mmTx.TxMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.t1
		}
	}

	if mmTx.TxMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmTx.TxMock.defaultExpectation.Counter, 1)
		mm_want := mmTx.TxMock.defaultExpectation.params
		mm_want_ptrs := mmTx.TxMock.defaultExpectation.paramPtrs

		mm_got := StorageMockTxParams{ctx}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmTx.t.Errorf("StorageMock.Tx got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmTx.TxMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmTx.t.Errorf("StorageMock.Tx got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmTx.TxMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmTx.TxMock.defaultExpectation.results
		if mm_results == nil {
			mmTx.t.Fatal("No results are set for the StorageMock.Tx")
		}
		return (*mm_results).t1
	}
	if mmTx.funcTx != nil {
		return mmTx.funcTx(ctx)
	}
	mmTx.t.Fatalf("Unexpected call to StorageMock.Tx. %v", ctx)
	return
}

// TxAfterCounter returns a count of finished StorageMock.Tx invocations
func (mmTx *StorageMock) TxAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmTx.afterTxCounter)
}

// TxBeforeCounter returns a count of StorageMock.Tx invocations
func (mmTx *StorageMock) TxBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmTx.beforeTxCounter)
}

// Calls returns a list of arguments used in each call to StorageMock.Tx.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmTx *mStorageMockTx) Calls() []*StorageMockTxParams {
	mmTx.mutex.RLock()

	argCopy := make([]*StorageMockTxParams, len(mmTx.callArgs))
	copy(argCopy, mmTx.callArgs)

	mmTx.mutex.RUnlock()

	return argCopy
}

// MinimockTxDone returns true if the count of the Tx invocations corresponds
// the number of defined expectations
func (m *StorageMock) MinimockTxDone() bool {
	if m.TxMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.TxMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.TxMock.invocationsDone()
}

// MinimockTxInspect logs each unmet expectation
func (m *StorageMock) MinimockTxInspect() {
	for _, e := range m.TxMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StorageMock.Tx at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterTxCounter := mm_atomic.LoadUint64(&m.afterTxCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.TxMock.defaultExpectation != nil && afterTxCounter < 1 {
		if m.TxMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StorageMock.Tx at\n%s", m.TxMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StorageMock.Tx at\n%s with params: %#v", m.TxMock.defaultExpectation.expectationOrigins.origin, *m.TxMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcTx != nil && afterTxCounter < 1 {
		m.t.Errorf("Expected call to StorageMock.Tx at\n%s", m.funcTxOrigin)
	}

	if !m.TxMock.invocationsDone() && afterTxCounter > 0 {
		m.t.Errorf("Expected %d calls to StorageMock.Tx at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.TxMock.expectedInvocations), m.TxMock.expectedInvocationsOrigin, afterTxCounter)
	}
}

type mStorageMockTxFactory struct {
	optional           bool
	mock               *StorageMock
	defaultExpectation *StorageMockTxFactoryExpectation
	expectations       []*StorageMockTxFactoryExpectation

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StorageMockTxFactoryExpectation specifies expectation struct of the Storage.TxFactory
type StorageMockTxFactoryExpectation struct {
	mock *StorageMock

	results      *StorageMockTxFactoryResults
	returnOrigin string
	Counter      uint64
}

// StorageMockTxFactoryResults contains results of the Storage.TxFactory
type StorageMockTxFactoryResults struct {
	f1 txPkg.Factory
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmTxFactory *mStorageMockTxFactory) Optional() *mStorageMockTxFactory {
	mmTxFactory.optional = true
	return mmTxFactory
}

// Expect sets up expected params for Storage.TxFactory
func (mmTxFactory *mStorageMockTxFactory) Expect() *mStorageMockTxFactory {
	if mmTxFactory.mock.funcTxFactory != nil {
		mmTxFactory.mock.t.Fatalf("StorageMock.TxFactory mock is already set by Set")
	}

	if mmTxFactory.defaultExpectation == nil {
		mmTxFactory.defaultExpectation = &StorageMockTxFactoryExpectation{}
	}

	return mmTxFactory
}

// Inspect accepts an inspector function that has same arguments as the Storage.TxFactory
func (mmTxFactory *mStorageMockTxFactory) Inspect(f func()) *mStorageMockTxFactory {
	if mmTxFactory.mock.inspectFuncTxFactory != nil {
		mmTxFactory.mock.t.Fatalf("Inspect function is already set for StorageMock.TxFactory")
	}

	mmTxFactory.mock.inspectFuncTxFactory = f

	return mmTxFactory
}

// Return sets up results that will be returned by Storage.TxFactory
func (mmTxFactory *mStorageMockTxFactory) Return(f1 txPkg.Factory) *StorageMock {
	if mmTxFactory.mock.funcTxFactory != nil {
		mmTxFactory.mock.t.Fatalf("StorageMock.TxFactory mock is already set by Set")
	}

	if mmTxFactory.defaultExpectation == nil {
		mmTxFactory.defaultExpectation = &StorageMockTxFactoryExpectation{mock: mmTxFactory.mock}
	}
	mmTxFactory.defaultExpectation.results = &StorageMockTxFactoryResults{f1}
	mmTxFactory.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmTxFactory.mock
}

// Set uses given function f to mock the Storage.TxFactory method
func (mmTxFactory *mStorageMockTxFactory) Set(f func() (f1 txPkg.Factory)) *StorageMock {
	if mmTxFactory.defaultExpectation != nil {
		mmTxFactory.mock.t.Fatalf("Default expectation is already set for the Storage.TxFactory method")
	}

	if len(mmTxFactory.expectations) > 0 {
		mmTxFactory.mock.t.Fatalf("Some expectations are already set for the Storage.TxFactory method")
	}

	mmTxFactory.mock.funcTxFactory = f
	mmTxFactory.mock.funcTxFactoryOrigin = minimock.CallerInfo(1)
	return mmTxFactory.mock
}

// Times sets number of times Storage.TxFactory should be invoked
func (mmTxFactory *mStorageMockTxFactory) Times(n uint64) *mStorageMockTxFactory {
	if n == 0 {
		mmTxFactory.mock.t.Fatalf("Times of StorageMock.TxFactory mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmTxFactory.expectedInvocations, n)
	mmTxFactory.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmTxFactory
}

func (mmTxFactory *mStorageMockTxFactory) invocationsDone() bool {
	if len(mmTxFactory.expectations) == 0 && mmTxFactory.defaultExpectation == nil && mmTxFactory.mock.funcTxFactory == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmTxFactory.mock.afterTxFactoryCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmTxFactory.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// TxFactory implements Storage
func (mmTxFactory *StorageMock) TxFactory() (f1 txPkg.Factory) {
	mm_atomic.AddUint64(&mmTxFactory.beforeTxFactoryCounter, 1)
	defer mm_atomic.AddUint64(&mmTxFactory.afterTxFactoryCounter, 1)

	mmTxFactory.t.Helper()

	if mmTxFactory.inspectFuncTxFactory != nil {
		mmTxFactory.inspectFuncTxFactory()
	}

	if mmTxFactory.TxFactoryMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmTxFactory.TxFactoryMock.defaultExpectation.Counter, 1)

		mm_results := mmTxFactory.TxFactoryMock.defaultExpectation.results
		if mm_results == nil {
			mmTxFactory.t.Fatal("No results are set for the StorageMock.TxFactory")
		}
		return (*mm_results).f1
	}
	if mmTxFactory.funcTxFactory != nil {
		return mmTxFactory.funcTxFactory()
	}
	mmTxFactory.t.Fatalf("Unexpected call to StorageMock.TxFactory.")
	return
}

// TxFactoryAfterCounter returns a count of finished StorageMock.TxFactory invocations
func (mmTxFactory *StorageMock) TxFactoryAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmTxFactory.afterTxFactoryCounter)
}

// TxFactoryBeforeCounter returns a count of StorageMock.TxFactory invocations
func (mmTxFactory *StorageMock) TxFactoryBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmTxFactory.beforeTxFactoryCounter)
}

// MinimockTxFactoryDone returns true if the count of the TxFactory invocations corresponds
// the number of defined expectations
func (m *StorageMock) MinimockTxFactoryDone() bool {
	if m.TxFactoryMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.TxFactoryMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.TxFactoryMock.invocationsDone()
}

// MinimockTxFactoryInspect logs each unmet expectation
func (m *StorageMock) MinimockTxFactoryInspect() {
	for _, e := range m.TxFactoryMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to StorageMock.TxFactory")
		}
	}

	afterTxFactoryCounter := mm_atomic.LoadUint64(&m.afterTxFactoryCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.TxFactoryMock.defaultExpectation != nil && afterTxFactoryCounter < 1 {
		m.t.Errorf("Expected call to StorageMock.TxFactory at\n%s", m.TxFactoryMock.defaultExpectation.returnOrigin)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcTxFactory != nil && afterTxFactoryCounter < 1 {
		m.t.Errorf("Expected call to StorageMock.TxFactory at\n%s", m.funcTxFactoryOrigin)
	}

	if !m.TxFactoryMock.invocationsDone() && afterTxFactoryCounter > 0 {
		m.t.Errorf("Expected %d calls to StorageMock.TxFactory at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.TxFactoryMock.expectedInvocations), m.TxFactoryMock.expectedInvocationsOrigin, afterTxFactoryCounter)
	}
}

type mStorageMockWatch struct {
	optional           bool
	mock               *StorageMock
	defaultExpectation *StorageMockWatchExpectation
	expectations       []*StorageMockWatchExpectation

	callArgs []*StorageMockWatchParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StorageMockWatchExpectation specifies expectation struct of the Storage.Watch
type StorageMockWatchExpectation struct {
	mock               *StorageMock
	params             *StorageMockWatchParams
	paramPtrs          *StorageMockWatchParamPtrs
	expectationOrigins StorageMockWatchExpectationOrigins
	results            *StorageMockWatchResults
	returnOrigin       string
	Counter            uint64
}

// StorageMockWatchParams contains parameters of the Storage.Watch
type StorageMockWatchParams struct {
	ctx context.Context
	key []byte
}

// StorageMockWatchParamPtrs contains pointers to parameters of the Storage.Watch
type StorageMockWatchParamPtrs struct {
	ctx *context.Context
	key *[]byte
}

// StorageMockWatchResults contains results of the Storage.Watch
type StorageMockWatchResults struct {
	ch1 <-chan watch.Event
}

// StorageMockWatchOrigins contains origins of expectations of the Storage.Watch
type StorageMockWatchExpectationOrigins struct {
	origin    string
	originCtx string
	originKey string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmWatch *mStorageMockWatch) Optional() *mStorageMockWatch {
	mmWatch.optional = true
	return mmWatch
}

// Expect sets up expected params for Storage.Watch
func (mmWatch *mStorageMockWatch) Expect(ctx context.Context, key []byte) *mStorageMockWatch {
	if mmWatch.mock.funcWatch != nil {
		mmWatch.mock.t.Fatalf("StorageMock.Watch mock is already set by Set")
	}

	if mmWatch.defaultExpectation == nil {
		mmWatch.defaultExpectation = &StorageMockWatchExpectation{}
	}

	if mmWatch.defaultExpectation.paramPtrs != nil {
		mmWatch.mock.t.Fatalf("StorageMock.Watch mock is already set by ExpectParams functions")
	}

	mmWatch.defaultExpectation.params = &StorageMockWatchParams{ctx, key}
	mmWatch.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmWatch.expectations {
		if minimock.Equal(e.params, mmWatch.defaultExpectation.params) {
			mmWatch.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmWatch.defaultExpectation.params)
		}
	}

	return mmWatch
}

// ExpectCtxParam1 sets up expected param ctx for Storage.Watch
func (mmWatch *mStorageMockWatch) ExpectCtxParam1(ctx context.Context) *mStorageMockWatch {
	if mmWatch.mock.funcWatch != nil {
		mmWatch.mock.t.Fatalf("StorageMock.Watch mock is already set by Set")
	}

	if mmWatch.defaultExpectation == nil {
		mmWatch.defaultExpectation = &StorageMockWatchExpectation{}
	}

	if mmWatch.defaultExpectation.params != nil {
		mmWatch.mock.t.Fatalf("StorageMock.Watch mock is already set by Expect")
	}

	if mmWatch.defaultExpectation.paramPtrs == nil {
		mmWatch.defaultExpectation.paramPtrs = &StorageMockWatchParamPtrs{}
	}
	mmWatch.defaultExpectation.paramPtrs.ctx = &ctx
	mmWatch.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmWatch
}

// ExpectKeyParam2 sets up expected param key for Storage.Watch
func (mmWatch *mStorageMockWatch) ExpectKeyParam2(key []byte) *mStorageMockWatch {
	if mmWatch.mock.funcWatch != nil {
		mmWatch.mock.t.Fatalf("StorageMock.Watch mock is already set by Set")
	}

	if mmWatch.defaultExpectation == nil {
		mmWatch.defaultExpectation = &StorageMockWatchExpectation{}
	}

	if mmWatch.defaultExpectation.params != nil {
		mmWatch.mock.t.Fatalf("StorageMock.Watch mock is already set by Expect")
	}

	if mmWatch.defaultExpectation.paramPtrs == nil {
		mmWatch.defaultExpectation.paramPtrs = &StorageMockWatchParamPtrs{}
	}
	mmWatch.defaultExpectation.paramPtrs.key = &key
	mmWatch.defaultExpectation.expectationOrigins.originKey = minimock.CallerInfo(1)

	return mmWatch
}

// Inspect accepts an inspector function that has same arguments as the Storage.Watch
func (mmWatch *mStorageMockWatch) Inspect(f func(ctx context.Context, key []byte)) *mStorageMockWatch {
	if mmWatch.mock.inspectFuncWatch != nil {
		mmWatch.mock.t.Fatalf("Inspect function is already set for StorageMock.Watch")
	}

	mmWatch.mock.inspectFuncWatch = f

	return mmWatch
}

// Return sets up results that will be returned by Storage.Watch
func (mmWatch *mStorageMockWatch) Return(ch1 <-chan watch.Event) *StorageMock {
	if mmWatch.mock.funcWatch != nil {
		mmWatch.mock.t.Fatalf("StorageMock.Watch mock is already set by Set")
	}

	if mmWatch.defaultExpectation == nil {
		mmWatch.defaultExpectation = &StorageMockWatchExpectation{mock: mmWatch.mock}
	}
	mmWatch.defaultExpectation.results = &StorageMockWatchResults{ch1}
	mmWatch.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmWatch.mock
}

// Set uses given function f to mock the Storage.Watch method
func (mmWatch *mStorageMockWatch) Set(f func(ctx context.Context, key []byte) (ch1 <-chan watch.Event)) *StorageMock {
	if mmWatch.defaultExpectation != nil {
		mmWatch.mock.t.Fatalf("Default expectation is already set for the Storage.Watch method")
	}

	if len(mmWatch.expectations) > 0 {
		mmWatch.mock.t.Fatalf("Some expectations are already set for the Storage.Watch method")
	}

	mmWatch.mock.funcWatch = f
	mmWatch.mock.funcWatchOrigin = minimock.CallerInfo(1)
	return mmWatch.mock
}

// When sets expectation for the Storage.Watch which will trigger the result defined by the following
// Then helper
func (mmWatch *mStorageMockWatch) When(ctx context.Context, key []byte) *StorageMockWatchExpectation {
	if mmWatch.mock.funcWatch != nil {
		mmWatch.mock.t.Fatalf("StorageMock.Watch mock is already set by Set")
	}

	expectation := &StorageMockWatchExpectation{
		mock:               mmWatch.mock,
		params:             &StorageMockWatchParams{ctx, key},
		expectationOrigins: StorageMockWatchExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmWatch.expectations = append(mmWatch.expectations, expectation)
	return expectation
}

// Then sets up Storage.Watch return parameters for the expectation previously defined by the When method
func (e *StorageMockWatchExpectation) Then(ch1 <-chan watch.Event) *StorageMock {
	e.results = &StorageMockWatchResults{ch1}
	return e.mock
}

// Times sets number of times Storage.Watch should be invoked
func (mmWatch *mStorageMockWatch) Times(n uint64) *mStorageMockWatch {
	if n == 0 {
		mmWatch.mock.t.Fatalf("Times of StorageMock.Watch mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmWatch.expectedInvocations, n)
	mmWatch.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmWatch
}

func (mmWatch *mStorageMockWatch) invocationsDone() bool {
	if len(mmWatch.expectations) == 0 && mmWatch.defaultExpectation == nil && mmWatch.mock.funcWatch == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmWatch.mock.afterWatchCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmWatch.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Watch implements Storage
func (mmWatch *StorageMock) Watch(ctx context.Context, key []byte) (ch1 <-chan watch.Event) {
	mm_atomic.AddUint64(&mmWatch.beforeWatchCounter, 1)
	defer mm_atomic.AddUint64(&mmWatch.afterWatchCounter, 1)

	mmWatch.t.Helper()

	if mmWatch.inspectFuncWatch != nil {
		mmWatch.inspectFuncWatch(ctx, key)
	}

	mm_params := StorageMockWatchParams{ctx, key}

	// Record call args
	mmWatch.WatchMock.mutex.Lock()
	mmWatch.WatchMock.callArgs = append(mmWatch.WatchMock.callArgs, &mm_params)
	mmWatch.WatchMock.mutex.Unlock()

	for _, e := range mmWatch.WatchMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ch1
		}
	}

	if mmWatch.WatchMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmWatch.WatchMock.defaultExpectation.Counter, 1)
		mm_want := mmWatch.WatchMock.defaultExpectation.params
		mm_want_ptrs := mmWatch.WatchMock.defaultExpectation.paramPtrs

		mm_got := StorageMockWatchParams{ctx, key}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmWatch.t.Errorf("StorageMock.Watch got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmWatch.WatchMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.key != nil && !minimock.Equal(*mm_want_ptrs.key, mm_got.key) {
				mmWatch.t.Errorf("StorageMock.Watch got unexpected parameter key, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmWatch.WatchMock.defaultExpectation.expectationOrigins.originKey, *mm_want_ptrs.key, mm_got.key, minimock.Diff(*mm_want_ptrs.key, mm_got.key))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmWatch.t.Errorf("StorageMock.Watch got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmWatch.WatchMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmWatch.WatchMock.defaultExpectation.results
		if mm_results == nil {
			mmWatch.t.Fatal("No results are set for the StorageMock.Watch")
		}
		return (*mm_results).ch1
	}
	if mmWatch.funcWatch != nil {
		return mmWatch.funcWatch(ctx, key)
	}
	mmWatch.t.Fatalf("Unexpected call to StorageMock.Watch. %v %v", ctx, key)
	return
}

// WatchAfterCounter returns a count of finished StorageMock.Watch invocations
func (mmWatch *StorageMock) WatchAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmWatch.afterWatchCounter)
}

// WatchBeforeCounter returns a count of StorageMock.Watch invocations
func (mmWatch *StorageMock) WatchBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmWatch.beforeWatchCounter)
}

// Calls returns a list of arguments used in each call to StorageMock.Watch.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmWatch *mStorageMockWatch) Calls() []*StorageMockWatchParams {
	mmWatch.mutex.RLock()

	argCopy := make([]*StorageMockWatchParams, len(mmWatch.callArgs))
	copy(argCopy, mmWatch.callArgs)

	mmWatch.mutex.RUnlock()

	return argCopy
}

// MinimockWatchDone returns true if the count of the Watch invocations corresponds
// the number of defined expectations
func (m *StorageMock) MinimockWatchDone() bool {
	if m.WatchMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.WatchMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.WatchMock.invocationsDone()
}

// MinimockWatchInspect logs each unmet expectation
func (m *StorageMock) MinimockWatchInspect() {
	for _, e := range m.WatchMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StorageMock.Watch at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterWatchCounter := mm_atomic.LoadUint64(&m.afterWatchCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.WatchMock.defaultExpectation != nil && afterWatchCounter < 1 {
		if m.WatchMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StorageMock.Watch at\n%s", m.WatchMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StorageMock.Watch at\n%s with params: %#v", m.WatchMock.defaultExpectation.expectationOrigins.origin, *m.WatchMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcWatch != nil && afterWatchCounter < 1 {
		m.t.Errorf("Expected call to StorageMock.Watch at\n%s", m.funcWatchOrigin)
	}

	if !m.WatchMock.invocationsDone() && afterWatchCounter > 0 {
		m.t.Errorf("Expected %d calls to StorageMock.Watch at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.WatchMock.expectedInvocations), m.WatchMock.expectedInvocationsOrigin, afterWatchCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *StorageMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockLockerFactoryInspect()

			m.MinimockNewLockerInspect()

			m.MinimockRangeInspect()

			m.MinimockTxInspect()

			m.MinimockTxFactoryInspect()

			m.MinimockWatchInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *StorageMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *StorageMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockLockerFactoryDone() &&
		m.MinimockNewLockerDone() &&
		m.MinimockRangeDone() &&
		m.MinimockTxDone() &&
		m.MinimockTxFactoryDone() &&
		m.MinimockWatchDone()
}
